import type { Question } from '@/types';

export const bscTriviaQuestions: Question[] = [
  {
    id: 'bsc-001',
    subject: 'bsc-trivia',
    language: 'en',
    difficulty: 1,
    question: 'Who is the president of the Baby-Sitters Club?',
    options: ['Mary Anne', 'Claudia', 'Kristy', 'Stacey'],
    correct: 2,
    explanation: 'Kristy Thomas is the president — it was her GREAT IDEA to start the club!',
    emoji: '👑',
    points: 10,
  },
  {
    id: 'bsc-002',
    subject: 'bsc-trivia',
    language: 'en',
    difficulty: 1,
    question: 'What is Claudia Kishi\'s favourite hobby?',
    options: ['Reading', 'Sports', 'Art and painting', 'Cooking'],
    correct: 2,
    explanation: 'Claudia LOVES art! She paints, draws, and creates amazing artwork. She also loves junk food!',
    emoji: '🎨',
    points: 10,
  },
  {
    id: 'bsc-003',
    subject: 'bsc-trivia',
    language: 'en',
    difficulty: 1,
    question: 'Which Baby-Sitter keeps a diary and is very shy?',
    options: ['Kristy', 'Mary Anne', 'Claudia', 'Dawn'],
    correct: 1,
    explanation: 'Mary Anne Spier! She writes in her diary and is quiet and sensitive — but also very kind!',
    emoji: '📔',
    points: 10,
  },
  {
    id: 'bsc-004',
    subject: 'bsc-trivia',
    language: 'en',
    difficulty: 2,
    question: 'If you were babysitting and a child fell and hurt their knee, what should you do FIRST?',
    options: [
      'Ignore it and keep playing',
      'Stay calm, clean the wound, and tell the parents',
      'Panic and call 911 immediately',
      'Give the child candy to stop crying',
    ],
    correct: 1,
    explanation: 'Stay calm, clean the wound gently, and inform the parents when they return. Good babysitters are responsible!',
    emoji: '🩹',
    points: 15,
  },
  {
    id: 'bsc-005',
    subject: 'bsc-trivia',
    language: 'en',
    difficulty: 1,
    question: 'What does BSC stand for?',
    options: ['Best Students Club', 'Baby-Sitters Club', 'Big Sisters Club', 'Books and Stories Club'],
    correct: 1,
    explanation: 'BSC = Baby-Sitters Club! Founded by Kristy Thomas with her great idea!',
    emoji: '📱',
    points: 10,
  },
  {
    id: 'bsc-006',
    subject: 'bsc-trivia',
    language: 'en',
    difficulty: 2,
    question: 'What quality makes Kristy a great leader?',
    options: [
      'She is the tallest',
      'She has great ideas and is organized',
      'She is the oldest',
      'She has the most experience',
    ],
    correct: 1,
    explanation: 'Kristy has GREAT IDEAS and is very organized! Good leaders think ahead and make plans!',
    emoji: '💡',
    points: 15,
  },
  {
    id: 'bsc-007',
    subject: 'bsc-trivia',
    language: 'en',
    difficulty: 1,
    question: 'Where does the BSC hold their meetings?',
    options: ['At school', 'In Claudia\'s room', 'In Kristy\'s house', 'At the library'],
    correct: 1,
    explanation: 'They meet in Claudia\'s bedroom because she has her own phone line!',
    emoji: '🏠',
    points: 10,
  },
  {
    id: 'bsc-008',
    subject: 'bsc-trivia',
    language: 'en',
    difficulty: 2,
    question: 'If you\'re babysitting two kids who are arguing, what is the BEST thing to do?',
    options: [
      'Tell them to stop and ignore them',
      'Take sides with one child',
      'Listen to both sides and help them find a solution together',
      'Send them both to their rooms',
    ],
    correct: 2,
    explanation: 'Great babysitters (and friends!) listen to both sides and help find a fair solution. That\'s what Mary Anne does!',
    emoji: '🤝',
    points: 15,
  },
  {
    id: 'bsc-009',
    subject: 'bsc-trivia',
    language: 'en',
    difficulty: 1,
    question: 'What is Stacey McGill\'s special medical condition?',
    options: ['Asthma', 'Diabetes', 'Allergies', 'A broken arm'],
    correct: 1,
    explanation: 'Stacey has diabetes and needs to be careful about what she eats. She is very brave about it!',
    emoji: '💉',
    points: 10,
  },
  {
    id: 'bsc-010',
    subject: 'bsc-trivia',
    language: 'en',
    difficulty: 2,
    question: 'What does a good babysitter always do?',
    options: [
      'Play video games while the kids watch TV',
      'Keep the children safe and have fun activities ready',
      'Invite her friends over',
      'Order food for herself',
    ],
    correct: 1,
    explanation: 'A good babysitter always prioritizes safety AND makes sure the kids have fun! Just like the BSC!',
    emoji: '⭐',
    points: 15,
  },
  {
    id: 'bsc-011',
    subject: 'bsc-trivia',
    language: 'en',
    difficulty: 3,
    question: 'In the BSC, who comes from California and loves health food?',
    options: ['Mallory', 'Jessi', 'Dawn', 'Abby'],
    correct: 2,
    explanation: 'Dawn Schafer moved from California! She loves healthy food and is laid-back and cool.',
    emoji: '🌊',
    points: 20,
  },
  {
    id: 'bsc-012',
    subject: 'bsc-trivia',
    language: 'en',
    difficulty: 2,
    question: 'Which BSC member wants to be a writer when she grows up?',
    options: ['Claudia', 'Stacey', 'Mallory', 'Kristy'],
    correct: 2,
    explanation: 'Mallory Pike wants to be an author and illustrator! She loves books and stories.',
    emoji: '✍️',
    points: 15,
  },
  {
    id: 'bsc-013',
    subject: 'bsc-trivia',
    language: 'en',
    difficulty: 1,
    question: 'What is important about being a good friend, just like in the BSC?',
    options: [
      'Always agreeing with everything they say',
      'Listening, being kind, and being there when they need you',
      'Only being friends when it\'s fun',
      'Being the most popular person',
    ],
    correct: 1,
    explanation: 'Good friends LISTEN, are KIND, and are there for each other — just like Kristy, Claudia, and Mary Anne!',
    emoji: '💜',
    points: 10,
  },
  {
    id: 'bsc-014',
    subject: 'bsc-trivia',
    language: 'en',
    difficulty: 2,
    question: 'Jessi Ramsey is talented at which art form?',
    options: ['Singing', 'Ballet dancing', 'Painting', 'Acting in plays'],
    correct: 1,
    explanation: 'Jessi Ramsey is a talented ballet dancer! She trains very hard and loves to perform.',
    emoji: '🩰',
    points: 15,
  },
  {
    id: 'bsc-015',
    subject: 'bsc-trivia',
    language: 'en',
    difficulty: 1,
    question: 'What does Mary Anne\'s best friend (who is also her stepsister) love?',
    options: ['Art', 'Sports', 'Health food and California', 'Math'],
    correct: 2,
    explanation: 'Dawn! Mary Anne and Dawn became best friends AND stepsisters. Dawn loves California and healthy food!',
    emoji: '🌻',
    points: 10,
  },
  {
    id: 'bsc-016',
    subject: 'bsc-trivia',
    language: 'en',
    difficulty: 3,
    question: 'The BSC uses a record book to track clients. This is an example of:',
    options: ['Being bossy', 'Being organized and professional', 'Having too many rules', 'Wasting time'],
    correct: 1,
    explanation: 'Being organized is a KEY skill! The record book helps them be reliable and professional — great life skills!',
    emoji: '📒',
    points: 20,
  },
];
