import type { Question } from '@/types';

export const bscTriviaQuestions2: Question[] = [
  {
    id: 'bsc-017', subject: 'bsc-trivia', language: 'en', difficulty: 1,
    question: 'What is Stacey McGill\'s favourite subject at school?',
    options: ['Art', 'Math', 'English', 'Science'],
    correct: 1, explanation: 'Stacey LOVES math! She\'s incredibly good at it. It\'s one of the things that makes her a great treasurer for the BSC!', emoji: '➕', points: 10,
  },
  {
    id: 'bsc-018', subject: 'bsc-trivia', language: 'en', difficulty: 1,
    question: 'What is the name of Kristy\'s little sister (adopted)?',
    options: ['Jenny', 'Emily Michelle', 'Karen', 'Claire'],
    correct: 1, explanation: 'Emily Michelle! She was adopted by Kristy\'s mum and stepfather Watson from Vietnam!', emoji: '🌸', points: 10,
  },
  {
    id: 'bsc-019', subject: 'bsc-trivia', language: 'en', difficulty: 2,
    question: 'What does the BSC use to keep track of their sitting jobs?',
    options: ['A phone app', 'The record book', 'Their memory', 'A chalkboard'],
    correct: 1, explanation: 'The BSC record book! Claudia keeps it and it has client info, schedules, and each sitter\'s availability!', emoji: '📒', points: 15,
  },
  {
    id: 'bsc-020', subject: 'bsc-trivia', language: 'en', difficulty: 1,
    question: 'What is Claudia\'s favourite snack that she hides in her room?',
    options: ['Chocolate cake', 'Junk food (chips, candy, etc.)', 'Fruit', 'Cookies only'],
    correct: 1, explanation: 'Claudia hides ALL kinds of junk food in her room — chips, candy, chocolate! Her parents want her to eat healthily!', emoji: '🍬', points: 10,
  },
  {
    id: 'bsc-021', subject: 'bsc-trivia', language: 'en', difficulty: 2,
    question: 'What does being a good babysitter teach you about responsibility?',
    options: [
      'Nothing — it\'s just fun',
      'You must keep children safe and be reliable',
      'Only how to play games',
      'How to cook for children',
    ],
    correct: 1, explanation: 'Babysitting teaches real responsibility: keeping kids safe, being on time, being reliable, and handling emergencies!', emoji: '⭐', points: 15,
  },
  {
    id: 'bsc-022', subject: 'bsc-trivia', language: 'en', difficulty: 1,
    question: 'Who is the BSC\'s treasurer?',
    options: ['Kristy', 'Mary Anne', 'Stacey', 'Dawn'],
    correct: 2, explanation: 'Stacey McGill is the BSC\'s treasurer! She\'s great with numbers and manages all the club\'s money!', emoji: '💰', points: 10,
  },
  {
    id: 'bsc-023', subject: 'bsc-trivia', language: 'en', difficulty: 2,
    question: 'If a child you\'re babysitting has an allergic reaction, what should you do?',
    options: [
      'Give them water and hope it gets better',
      'Call their parents immediately and use their epi-pen if available',
      'Put them to bed',
      'Give them food to distract them',
    ],
    correct: 1, explanation: 'For allergic reactions: stay calm, call parents immediately, use their emergency medication (like an epi-pen) if needed!', emoji: '🚨', points: 15,
  },
  {
    id: 'bsc-024', subject: 'bsc-trivia', language: 'en', difficulty: 1,
    question: 'What city do the BSC members live in?',
    options: ['New York', 'Boston', 'Stoneybrook', 'Greenwich'],
    correct: 2, explanation: 'Stoneybrook, Connecticut! It\'s a fictional town where all the BSC adventures happen!', emoji: '🏘️', points: 10,
  },
  {
    id: 'bsc-025', subject: 'bsc-trivia', language: 'en', difficulty: 2,
    question: 'What nationality is Claudia\'s heritage?',
    options: ['Chinese', 'Japanese', 'Korean', 'Vietnamese'],
    correct: 1, explanation: 'Claudia Kishi is Japanese-American! Her family\'s Japanese heritage is an important part of her identity!', emoji: '🇯🇵', points: 15,
  },
  {
    id: 'bsc-026', subject: 'bsc-trivia', language: 'en', difficulty: 1,
    question: 'What is Mallory\'s dream career?',
    options: ['Doctor', 'Teacher', 'Author and illustrator', 'Dancer'],
    correct: 2, explanation: 'Mallory Pike dreams of being an author and illustrator! She loves writing stories and has many younger siblings to inspire her!', emoji: '✍️', points: 10,
  },
  {
    id: 'bsc-027', subject: 'bsc-trivia', language: 'en', difficulty: 2,
    question: 'What is the best way to handle a disagreement with a friend?',
    options: [
      'Stop being friends',
      'Ignore the problem',
      'Talk honestly and listen to each other',
      'Always do what they want',
    ],
    correct: 2, explanation: 'The BSC shows us: talk honestly, listen actively, and find a solution together. That\'s how real friendships survive!', emoji: '🤝', points: 15,
  },
  {
    id: 'bsc-028', subject: 'bsc-trivia', language: 'en', difficulty: 1,
    question: 'What does Mary Anne\'s best friend Dawn love to eat?',
    options: ['Pizza', 'Burgers', 'Health food and tofu', 'Candy'],
    correct: 2, explanation: 'Dawn loves health food! She\'s from California and eats things like tofu, sprouts, and natural snacks!', emoji: '🥗', points: 10,
  },
  {
    id: 'bsc-029', subject: 'bsc-trivia', language: 'en', difficulty: 3,
    question: 'Who wrote the Baby-Sitters Club series?',
    options: ['Beverly Cleary', 'Ann M. Martin', 'Judy Blume', 'Roald Dahl'],
    correct: 1, explanation: 'Ann M. Martin created the BSC! She published the first book in 1986. There are over 200 books in the series!', emoji: '📖', points: 20,
  },
  {
    id: 'bsc-030', subject: 'bsc-trivia', language: 'en', difficulty: 2,
    question: 'Jessi and Mallory are the BSC\'s "junior officers." What does this mean?',
    options: [
      'They are less important members',
      'They are younger and mainly sit afternoons/weekends',
      'They do less work',
      'They don\'t go to meetings',
    ],
    correct: 1, explanation: 'Junior officers are younger (11) and mainly take afternoon/weekend jobs so the older members can sit at night!', emoji: '👶', points: 15,
  },
  {
    id: 'bsc-031', subject: 'bsc-trivia', language: 'en', difficulty: 1,
    question: 'How many calls does the BSC get during their Monday/Wednesday/Friday meetings?',
    options: ['Just 1', 'None — they use a website', 'Many — parents call the one number', 'They go door to door'],
    correct: 2, explanation: 'Parents call ONE number (Claudia\'s) and reach multiple sitters at once — that\'s Kristy\'s great idea! Efficient!', emoji: '📞', points: 10,
  },
  {
    id: 'bsc-032', subject: 'bsc-trivia', language: 'en', difficulty: 2,
    question: 'What is in the BSC\'s Kid-Kits?',
    options: [
      'Emergency medical supplies',
      'Toys, books, and games to entertain children',
      'Snacks for the babysitter',
      'Money for emergencies',
    ],
    correct: 1, explanation: 'Kid-Kits are boxes filled with toys, books, games, and art supplies that sitters bring to jobs! Kids love them!', emoji: '🎁', points: 15,
  },
  {
    id: 'bsc-033', subject: 'bsc-trivia', language: 'en', difficulty: 1,
    question: 'What is Kristy\'s stepfather\'s first name?',
    options: ['Patrick', 'Watson', 'Charlie', 'David'],
    correct: 1, explanation: 'Watson Brewer! He\'s very wealthy and has children Karen and Andrew from his first marriage!', emoji: '👨‍👩‍👧‍👦', points: 10,
  },
  {
    id: 'bsc-034', subject: 'bsc-trivia', language: 'en', difficulty: 2,
    question: 'What is an important quality that ALL BSC members share?',
    options: [
      'They\'re all the same age',
      'They all live on the same street',
      'They all genuinely care about the children they sit for',
      'They all have perfect grades',
    ],
    correct: 2, explanation: 'Every BSC member genuinely CARES about the kids! That\'s what makes them great sitters — they\'re not just doing it for money!', emoji: '❤️', points: 15,
  },
  {
    id: 'bsc-035', subject: 'bsc-trivia', language: 'en', difficulty: 3,
    question: 'In the Netflix/graphic novel version, which member joins the BSC first after Kristy, Claudia, and Mary Anne?',
    options: ['Stacey', 'Dawn', 'Mallory', 'Jessi'],
    correct: 0, explanation: 'Stacey McGill joins fourth! She moves from New York City and brings big-city style to Stoneybrook!', emoji: '🌆', points: 20,
  },
  {
    id: 'bsc-036', subject: 'bsc-trivia', language: 'en', difficulty: 1,
    question: 'What does "reliable" mean, which is a key BSC value?',
    options: [
      'Always being right',
      'Being trusted to do what you say you\'ll do',
      'Being the fastest',
      'Having the most friends',
    ],
    correct: 1, explanation: '"Reliable" = trustworthy, you do what you promise! If you say you\'ll be somewhere at 5pm, you\'re there at 5pm!', emoji: '⏰', points: 10,
  },
  {
    id: 'bsc-037', subject: 'bsc-trivia', language: 'en', difficulty: 2,
    question: 'Jessi Ramsey loves ballet. What is the name of the famous ballet school she trains at?',
    options: [
      'Stoneybrook Academy of Dance',
      'Madame Noelle\'s school',
      'The Stamford Ballet',
      'The Connecticut Dance Centre',
    ],
    correct: 1, explanation: 'Jessi trains with Madame Noelle! She\'s very dedicated and often gets the lead role in performances!', emoji: '🩰', points: 15,
  },
  {
    id: 'bsc-038', subject: 'bsc-trivia', language: 'en', difficulty: 1,
    question: 'What is the first thing you should do before babysitting someone new?',
    options: [
      'Start playing immediately',
      'Learn about the family: emergency numbers, allergies, rules',
      'Turn on the TV',
      'Look for snacks',
    ],
    correct: 1, explanation: 'Get informed first! Know emergency numbers, allergies, bedtimes, rules, and where parents are. Preparation = safety!', emoji: '📋', points: 10,
  },
  {
    id: 'bsc-039', subject: 'bsc-trivia', language: 'en', difficulty: 2,
    question: 'What colour is Claudia\'s room described as in the books?',
    options: ['Pink and white', 'Filled with her artwork and colourful decorations', 'Plain and simple', 'Blue'],
    correct: 1, explanation: 'Claudia\'s room is filled with her artwork, colourful decorations, and paintings! It reflects her creative personality!', emoji: '🎨', points: 15,
  },
  {
    id: 'bsc-040', subject: 'bsc-trivia', language: 'en', difficulty: 3,
    question: 'What is the name of Claudia\'s older sister who is a genius?',
    options: ['Mimi', 'Peaches', 'Janine', 'Jenny'],
    correct: 2, explanation: 'Janine Kishi is Claudia\'s brilliant older sister who takes college courses! Claudia sometimes feels overshadowed by her!', emoji: '🎓', points: 20,
  },
  {
    id: 'bsc-041', subject: 'bsc-trivia', language: 'en', difficulty: 1,
    question: 'What does "empathy" mean — something the BSC always practices?',
    options: [
      'Being strong',
      'Understanding and sharing others\' feelings',
      'Being very smart',
      'Working alone',
    ],
    correct: 1, explanation: 'Empathy = understanding how others feel! Mary Anne is known for being the most empathetic BSC member — she cries at everything!', emoji: '💜', points: 10,
  },
  {
    id: 'bsc-042', subject: 'bsc-trivia', language: 'en', difficulty: 2,
    question: 'What is the name of Mary Anne\'s cat?',
    options: ['Mochi', 'Tigger', 'Fluffy', 'Whiskers'],
    correct: 1, explanation: 'Tigger is Mary Anne\'s grey kitten! He\'s very playful and Mary Anne loves him!', emoji: '🐱', points: 15,
  },
  {
    id: 'bsc-043', subject: 'bsc-trivia', language: 'en', difficulty: 1,
    question: 'What is a "sit-in"? (in BSC context)',
    options: [
      'Sitting in a chair all day',
      'When multiple BSC members sit together for a difficult job',
      'A protest',
      'When members read silently',
    ],
    correct: 1, explanation: 'A sit-in is when two or more members work the same job together — usually for a big family or a challenging situation!', emoji: '👫', points: 10,
  },
  {
    id: 'bsc-044', subject: 'bsc-trivia', language: 'en', difficulty: 2,
    question: 'What is the name of the Johanssen family\'s daughter who the BSC often sits for?',
    options: ['Jenny', 'Charlotte', 'Becca', 'Kristy'],
    correct: 1, explanation: 'Charlotte Johanssen! She and Stacey have a special friendship. Charlotte is shy but very sweet!', emoji: '🌸', points: 15,
  },
  {
    id: 'bsc-045', subject: 'bsc-trivia', language: 'en', difficulty: 3,
    question: 'What important lesson do the BSC books teach about friendship?',
    options: [
      'Friends must be exactly alike',
      'You should only have one best friend',
      'True friendship survives differences and disagreements',
      'Friends should never argue',
    ],
    correct: 2, explanation: 'The BSC members are very different but remain close friends! Real friendships survive disagreements and different personalities!', emoji: '🌈', points: 20,
  },
  {
    id: 'bsc-046', subject: 'bsc-trivia', language: 'en', difficulty: 1,
    question: 'What makes Kristy such a good leader?',
    options: [
      'She is the tallest and loudest',
      'She has great ideas and cares about everyone',
      'She has the most money',
      'She\'s been friends with everyone the longest',
    ],
    correct: 1, explanation: 'Kristy is a great leader because she has GREAT IDEAS, cares about her team, and always thinks about improving the club!', emoji: '👑', points: 10,
  },
  {
    id: 'bsc-047', subject: 'bsc-trivia', language: 'en', difficulty: 2,
    question: 'Who is Jessi Ramsey\'s best friend in the BSC?',
    options: ['Claudia', 'Stacey', 'Mallory', 'Mary Anne'],
    correct: 2, explanation: 'Mallory Pike and Jessi Ramsey are best friends! They\'re both "junior officers" and love reading and creative writing/dancing!', emoji: '👭', points: 15,
  },
  {
    id: 'bsc-048', subject: 'bsc-trivia', language: 'en', difficulty: 1,
    question: 'What activity does Abby Stevenson love?',
    options: ['Reading', 'Art', 'Sports, especially soccer', 'Dancing'],
    correct: 2, explanation: 'Abby loves sports — especially soccer! She joined the BSC later as an alternate officer. She\'s also very funny!', emoji: '⚽', points: 10,
  },
  {
    id: 'bsc-049', subject: 'bsc-trivia', language: 'en', difficulty: 2,
    question: 'The BSC book series began in which decade?',
    options: ['1970s', '1980s', '1990s', '2000s'],
    correct: 1, explanation: 'The first BSC book was published in 1986! The series was hugely popular throughout the late 1980s and 1990s!', emoji: '📅', points: 15,
  },
  {
    id: 'bsc-050', subject: 'bsc-trivia', language: 'en', difficulty: 3,
    question: 'What is the most important reason to keep a notebook about babysitting experiences?',
    options: [
      'To gossip about families',
      'To share information so all members can give the best care',
      'To prove you worked hard',
      'To remember fun stories',
    ],
    correct: 1, explanation: 'The BSC notebook helps ALL members know each child\'s likes, fears, and needs. Shared knowledge = better care for every child!', emoji: '📓', points: 20,
  },
];
