import type { Question } from '@/types';

export const enEnglishQuestions2: Question[] = [
  {
    id: 'en-017', subject: 'en-english', language: 'en', difficulty: 1,
    question: 'Which word is spelled correctly?',
    options: ['beleive', 'believe', 'beleeve', 'beleve'],
    correct: 1, explanation: '"Believe" — tricky! Remember: beLIEve (there\'s a LIE in believe). Or: i before e except after c!', emoji: '💭', points: 10,
  },
  {
    id: 'en-018', subject: 'en-english', language: 'en', difficulty: 1,
    question: 'What is the plural of "foot"?',
    options: ['foots', 'feets', 'feet', 'foot'],
    correct: 2, explanation: '"Foot" → "feet". Irregular plural! Like tooth → teeth, goose → geese!', emoji: '👣', points: 10,
  },
  {
    id: 'en-019', subject: 'en-english', language: 'en', difficulty: 2,
    question: 'Choose the correct sentence:',
    options: [
      'Yesterday I go to the library.',
      'Yesterday I goed to the library.',
      'Yesterday I went to the library.',
      'Yesterday I gone to the library.',
    ],
    correct: 2, explanation: '"Go" is irregular! Past tense → "went". I go / I went / I have gone!', emoji: '📚', points: 15,
  },
  {
    id: 'en-020', subject: 'en-english', language: 'en', difficulty: 1,
    question: 'Which word means "very small"?',
    options: ['enormous', 'giant', 'tiny', 'huge'],
    correct: 2, explanation: '"Tiny" means very small! Synonyms: little, miniature, microscopic. A fairy is tiny!', emoji: '🧚', points: 10,
  },
  {
    id: 'en-021', subject: 'en-english', language: 'en', difficulty: 2,
    question: 'Fill in the blank: "She has ___ her homework already."',
    options: ['finish', 'finishing', 'finished', 'finishes'],
    correct: 2, explanation: '"Has + past participle" = present perfect. "She has finished" means she\'s done now!', emoji: '✅', points: 15,
  },
  {
    id: 'en-022', subject: 'en-english', language: 'en', difficulty: 1,
    question: 'What does the prefix "un-" mean?',
    options: ['very', 'again', 'not', 'before'],
    correct: 2, explanation: '"Un-" means NOT: unhappy = not happy, unsafe = not safe, unfair = not fair!', emoji: '🚫', points: 10,
  },
  {
    id: 'en-023', subject: 'en-english', language: 'en', difficulty: 2,
    question: 'Which sentence uses a simile correctly?',
    options: [
      'She is a lion.',
      'She is brave.',
      'She is as brave as a lion.',
      'She lions.',
    ],
    correct: 2, explanation: 'A simile compares using "as...as" or "like". "As brave as a lion" = very brave!', emoji: '🦁', points: 15,
  },
  {
    id: 'en-024', subject: 'en-english', language: 'en', difficulty: 1,
    question: 'What is the correct possessive: "The book belongs to Mary Anne."',
    options: ['Mary Annes book', 'Mary Anne\'s book', 'Mary Annes\' book', 'book of Mary Anne'],
    correct: 1, explanation: 'Add apostrophe + s for possession: Mary Anne\'s book = the book belonging to Mary Anne!', emoji: '📗', points: 10,
  },
  {
    id: 'en-025', subject: 'en-english', language: 'en', difficulty: 2,
    question: 'Choose the comparative form of "good":',
    options: ['gooder', 'more good', 'better', 'best'],
    correct: 2, explanation: '"Good" is irregular! good → better → best. NOT "more good"!', emoji: '⭐', points: 15,
  },
  {
    id: 'en-026', subject: 'en-english', language: 'en', difficulty: 1,
    question: 'What type of word is "quickly" in "She ran quickly"?',
    options: ['noun', 'verb', 'adjective', 'adverb'],
    correct: 3, explanation: '"Quickly" is an adverb — it describes HOW she ran. Most adverbs end in -ly!', emoji: '💨', points: 10,
  },
  {
    id: 'en-027', subject: 'en-english', language: 'en', difficulty: 2,
    question: 'Which word has the "-tion" suffix meaning "the act of"?',
    options: ['nation', 'action', 'question', 'emotion'],
    correct: 1, explanation: 'All have -tion! But "action" means "the act of acting". The -tion suffix often makes nouns from verbs!', emoji: '🎬', points: 15,
  },
  {
    id: 'en-028', subject: 'en-english', language: 'en', difficulty: 1,
    question: 'What is the opposite of "ancient"?',
    options: ['old', 'modern', 'big', 'dark'],
    correct: 1, explanation: '"Ancient" means very old. Its opposite is "modern" = new/recent!', emoji: '🏛️', points: 10,
  },
  {
    id: 'en-029', subject: 'en-english', language: 'en', difficulty: 2,
    question: 'Choose the correct pronoun: "___ and I went to the library."',
    options: ['Me', 'Her', 'She', 'Him'],
    correct: 2, explanation: 'Use subject pronouns (I, she, he, we, they) as the subject of a sentence. "She and I went" — not "Her and I"!', emoji: '👫', points: 15,
  },
  {
    id: 'en-030', subject: 'en-english', language: 'en', difficulty: 3,
    question: 'What is the meaning of "perseverance"?',
    options: [
      'Being very smart',
      'Giving up easily',
      'Continuing to try even when it\'s hard',
      'Being very fast',
    ],
    correct: 2, explanation: 'Perseverance = keep trying even when it\'s difficult! Kristy showed perseverance when starting the BSC!', emoji: '💪', points: 20,
  },
  {
    id: 'en-031', subject: 'en-english', language: 'en', difficulty: 1,
    question: 'Which word rhymes with "night"?',
    options: ['knit', 'neat', 'write', 'fight'],
    correct: 3, explanation: 'Night and fight both end with the "-ight" sound! night, light, right, sight, fight, might!', emoji: '🌙', points: 10,
  },
  {
    id: 'en-032', subject: 'en-english', language: 'en', difficulty: 2,
    question: 'What is a compound word?',
    options: [
      'A very long word',
      'Two words joined together to make one',
      'A word with a prefix',
      'A word that rhymes',
    ],
    correct: 1, explanation: 'A compound word = two words joined! Examples: sunshine (sun+shine), bookcase, butterfly, football!', emoji: '🔗', points: 15,
  },
  {
    id: 'en-033', subject: 'en-english', language: 'en', difficulty: 1,
    question: 'Which word is a proper noun?',
    options: ['city', 'mountain', 'London', 'river'],
    correct: 2, explanation: '"London" is a proper noun — it\'s the name of a specific city. Proper nouns always start with a capital letter!', emoji: '🏙️', points: 10,
  },
  {
    id: 'en-034', subject: 'en-english', language: 'en', difficulty: 2,
    question: 'Choose the superlative: "She is the ___ student in the class."',
    options: ['smart', 'smarter', 'more smart', 'smartest'],
    correct: 3, explanation: 'Superlative = THE most. One-syllable adjectives: add -est. smart → smarter → smartest!', emoji: '🏆', points: 15,
  },
  {
    id: 'en-035', subject: 'en-english', language: 'en', difficulty: 1,
    question: 'What does "frequent" mean?',
    options: ['rare', 'happening often', 'very large', 'very small'],
    correct: 1, explanation: '"Frequent" = happening often! "I frequently visit the library" = I go there often!', emoji: '🔄', points: 10,
  },
  {
    id: 'en-036', subject: 'en-english', language: 'en', difficulty: 2,
    question: 'Fill in: "If I ___ a wizard, I would go to Hogwarts."',
    options: ['am', 'was', 'were', 'be'],
    correct: 2, explanation: '"If I were" = conditional (imaginary situation). "Were" is used for all persons in conditional sentences!', emoji: '🧙', points: 15,
  },
  {
    id: 'en-037', subject: 'en-english', language: 'en', difficulty: 1,
    question: 'Which word is spelled correctly?',
    options: ['recieve', 'receve', 'receive', 'recive'],
    correct: 2, explanation: '"Receive" — the rule "i before e EXCEPT after c" applies here: rec-EI-ve!', emoji: '📬', points: 10,
  },
  {
    id: 'en-038', subject: 'en-english', language: 'en', difficulty: 2,
    question: 'What is the past tense of "write"?',
    options: ['writed', 'wrote', 'written', 'writ'],
    correct: 1, explanation: '"Write" → "wrote" (simple past). "Written" is the past participle (I have written)!', emoji: '✍️', points: 15,
  },
  {
    id: 'en-039', subject: 'en-english', language: 'en', difficulty: 1,
    question: 'Choose the correct article: "___ hour passed quickly."',
    options: ['A', 'An', 'The', 'Some'],
    correct: 1, explanation: '"An hour" — "h" in "hour" is silent, so it sounds like "an our" (vowel sound). Use "an" before vowel sounds!', emoji: '⏰', points: 10,
  },
  {
    id: 'en-040', subject: 'en-english', language: 'en', difficulty: 3,
    question: 'What literary device is used in: "The wind whispered through the trees"?',
    options: ['Rhyme', 'Personification', 'Alliteration', 'Simile'],
    correct: 1, explanation: 'Personification = giving human qualities to non-human things. Wind can\'t really whisper — that\'s a human action!', emoji: '🌳', points: 20,
  },
  {
    id: 'en-041', subject: 'en-english', language: 'en', difficulty: 1,
    question: 'What is the contraction for "they are"?',
    options: ['there', 'their', 'they\'re', 'theyre'],
    correct: 2, explanation: '"They\'re" = they are. The apostrophe replaces the missing letter "a". They\'re going to the library!', emoji: '📝', points: 10,
  },
  {
    id: 'en-042', subject: 'en-english', language: 'en', difficulty: 2,
    question: 'Which sentence has correct subject-verb agreement?',
    options: [
      'The girls plays soccer.',
      'She play piano.',
      'He runs every morning.',
      'They runs to school.',
    ],
    correct: 2, explanation: '"He runs" — with he/she/it, add -s to the verb in simple present. The others are wrong!', emoji: '🏃', points: 15,
  },
  {
    id: 'en-043', subject: 'en-english', language: 'en', difficulty: 1,
    question: 'What is alliteration?',
    options: [
      'Words that rhyme',
      'Repeated consonant sounds at the start of words',
      'A type of poem',
      'A very long sentence',
    ],
    correct: 1, explanation: 'Alliteration = same starting sound! Example: "Peter Piper picked a peck" — all start with P!', emoji: '🔤', points: 10,
  },
  {
    id: 'en-044', subject: 'en-english', language: 'en', difficulty: 2,
    question: 'Choose the right word: "The book is ___ the table."',
    options: ['in', 'on', 'at', 'to'],
    correct: 1, explanation: '"On" indicates position on a surface. The book is ON the table (touching the surface from above)!', emoji: '📖', points: 15,
  },
  {
    id: 'en-045', subject: 'en-english', language: 'en', difficulty: 1,
    question: 'Which word means "to look at something carefully"?',
    options: ['glance', 'observe', 'glimpse', 'peep'],
    correct: 1, explanation: '"Observe" means to watch carefully and attentively. Scientists observe, detectives observe!', emoji: '🔍', points: 10,
  },
  {
    id: 'en-046', subject: 'en-english', language: 'en', difficulty: 2,
    question: 'Choose the correct form: "By tomorrow, she ___ the book."',
    options: [
      'will finish',
      'will have finished',
      'finished',
      'has finished',
    ],
    correct: 1, explanation: '"Will have finished" = future perfect. An action that will be COMPLETE before a future point!', emoji: '📚', points: 15,
  },
  {
    id: 'en-047', subject: 'en-english', language: 'en', difficulty: 1,
    question: 'Which word is a conjunction?',
    options: ['slowly', 'beautiful', 'because', 'tree'],
    correct: 2, explanation: '"Because" is a conjunction — it joins two ideas together! Examples: and, but, or, because, although, when!', emoji: '🔗', points: 10,
  },
  {
    id: 'en-048', subject: 'en-english', language: 'en', difficulty: 3,
    question: 'What is the meaning of "meticulous"?',
    options: [
      'Very fast',
      'Very careful about details',
      'Very loud',
      'Very creative',
    ],
    correct: 1, explanation: '"Meticulous" = extremely careful about every small detail. Hermione is meticulous about her homework!', emoji: '🔎', points: 20,
  },
  {
    id: 'en-049', subject: 'en-english', language: 'en', difficulty: 1,
    question: 'How many syllables does "fantastic" have?',
    options: ['2', '3', '4', '5'],
    correct: 1, explanation: 'Fan-tas-tic = 3 syllables! Clap your hands to count: CLAP-CLAP-CLAP!', emoji: '👏', points: 10,
  },
  {
    id: 'en-050', subject: 'en-english', language: 'en', difficulty: 2,
    question: 'Fill in the blank: "Neither Harry ___ Ron knew the answer."',
    options: ['or', 'nor', 'and', 'but'],
    correct: 1, explanation: '"Neither...nor" go together! Neither A nor B. Either A or B. These are paired conjunctions!', emoji: '🤷', points: 15,
  },
  {
    id: 'en-051', subject: 'en-english', language: 'en', difficulty: 1,
    question: 'What does "W-O-R-K" spell?',
    options: ['walk', 'word', 'work', 'worm'],
    correct: 2, explanation: 'W-O-R-K = "work"! Spelling is important — Hermione would get this right!', emoji: '💼', points: 10,
  },
  {
    id: 'en-052', subject: 'en-english', language: 'en', difficulty: 2,
    question: 'What is the meaning of "transparent"?',
    options: ['very dark', 'you can see through it', 'very heavy', 'very soft'],
    correct: 1, explanation: '"Transparent" = you can see through it! Like glass or water. The prefix "trans" = through!', emoji: '🪟', points: 15,
  },
  {
    id: 'en-053', subject: 'en-english', language: 'en', difficulty: 1,
    question: 'Choose the correct homophone: "I can ___ the music." (hear/here)',
    options: ['here', 'hear', 'hire', 'hair'],
    correct: 1, explanation: '"Hear" = to listen. "Here" = this place. Can you HEAR? Your EAR is in hEAR!', emoji: '👂', points: 10,
  },
  {
    id: 'en-054', subject: 'en-english', language: 'en', difficulty: 2,
    question: 'Which sentence is punctuated correctly?',
    options: [
      'Claudia loves art painting and crafts',
      'Claudia loves art, painting, and crafts.',
      'Claudia loves, art painting, and crafts.',
      'Claudia, loves art painting and crafts.',
    ],
    correct: 1, explanation: 'Use commas to separate items in a list! "art, painting, and crafts" — comma before "and" in a list is optional but recommended!', emoji: '✏️', points: 15,
  },
  {
    id: 'en-055', subject: 'en-english', language: 'en', difficulty: 3,
    question: 'What is the meaning of the idiom "to hit the books"?',
    options: [
      'To damage books',
      'To study hard',
      'To go to the library',
      'To throw books',
    ],
    correct: 1, explanation: '"Hit the books" is an idiom meaning to study! Idioms have meanings different from their literal words!', emoji: '📚', points: 20,
  },
  {
    id: 'en-056', subject: 'en-english', language: 'en', difficulty: 1,
    question: 'What is the past tense of "run"?',
    options: ['runned', 'ran', 'ranned', 'runs'],
    correct: 1, explanation: '"Run" → "ran" — irregular verb! I run every day. Yesterday I ran to school!', emoji: '🏃', points: 10,
  },
  {
    id: 'en-057', subject: 'en-english', language: 'en', difficulty: 2,
    question: 'Which word is a synonym of "intelligent"?',
    options: ['foolish', 'clever', 'tired', 'small'],
    correct: 1, explanation: '"Intelligent" and "clever" both mean smart! Other synonyms: bright, wise, sharp, brilliant!', emoji: '🧠', points: 15,
  },
  {
    id: 'en-058', subject: 'en-english', language: 'en', difficulty: 1,
    question: 'What does the suffix "-less" mean?',
    options: ['full of', 'without', 'small', 'again'],
    correct: 1, explanation: '"-less" means WITHOUT: careless = without care, hopeless = without hope, homeless!', emoji: '➖', points: 10,
  },
  {
    id: 'en-059', subject: 'en-english', language: 'en', difficulty: 2,
    question: 'Choose the correct word: "I ___ to school every day." (past habit)',
    options: ['use to go', 'used to go', 'used to went', 'uses to go'],
    correct: 1, explanation: '"Used to + verb" describes a past habit or state. "I used to go" = I did this regularly before but not now!', emoji: '🎒', points: 15,
  },
  {
    id: 'en-060', subject: 'en-english', language: 'en', difficulty: 3,
    question: 'What does "benevolent" mean?',
    options: [
      'Very clever',
      'Feeling jealousy',
      'Kind and giving',
      'Feeling angry',
    ],
    correct: 2, explanation: '"Benevolent" = kind and giving to others. "Bene" = good (in Latin). Like "benefit"! Dumbledore is benevolent!', emoji: '❤️', points: 20,
  },
  {
    id: 'en-061', subject: 'en-english', language: 'en', difficulty: 1,
    question: 'How do you spell the number "forty"?',
    options: ['fourty', 'forty', 'fortey', 'fourtie'],
    correct: 1, explanation: '"Forty" — no U! Unlike "four" and "fourteen", "forty" has NO U. A tricky spelling!', emoji: '4️⃣0️⃣', points: 10,
  },
  {
    id: 'en-062', subject: 'en-english', language: 'en', difficulty: 2,
    question: 'Which sentence uses the correct verb tense?',
    options: [
      'She is reading the book when he arrived.',
      'She was reading the book when he arrived.',
      'She read the book when he arrived.',
      'She reads the book when he arrives.',
    ],
    correct: 1, explanation: 'Past continuous (was reading) + simple past (arrived) shows an ongoing action interrupted by another!', emoji: '📖', points: 15,
  },
  {
    id: 'en-063', subject: 'en-english', language: 'en', difficulty: 1,
    question: 'What word means "to make someone feel better when they are sad"?',
    options: ['ignore', 'tease', 'comfort', 'confuse'],
    correct: 2, explanation: '"Comfort" means to make someone feel better. Mary Anne is great at comforting her friends!', emoji: '🤗', points: 10,
  },
  {
    id: 'en-064', subject: 'en-english', language: 'en', difficulty: 2,
    question: 'What does the word "annual" mean?',
    options: ['every day', 'every week', 'every month', 'every year'],
    correct: 3, explanation: '"Annual" = every year! "Annum" is Latin for year. Annual checkup, annual celebration!', emoji: '📅', points: 15,
  },
  {
    id: 'en-065', subject: 'en-english', language: 'en', difficulty: 3,
    question: 'Identify the dependent clause: "Although it was raining, we went to the park."',
    options: [
      '"we went to the park"',
      '"Although it was raining"',
      '"Although it"',
      '"to the park"',
    ],
    correct: 1, explanation: '"Although it was raining" is dependent — it can\'t stand alone as a sentence! It needs the main clause!', emoji: '🌧️', points: 20,
  },
  {
    id: 'en-066', subject: 'en-english', language: 'en', difficulty: 1,
    question: 'Which word describes how something sounds, looks, or feels? "The fluffy kitten..."',
    options: ['runs', 'fluffy', 'kitten', 'the'],
    correct: 1, explanation: '"Fluffy" is an adjective — it describes what the kitten is LIKE! Adjectives describe nouns!', emoji: '🐱', points: 10,
  },
];
