import type { Question } from '@/types';

export const enEnglishQuestions: Question[] = [
  {
    id: 'en-001',
    subject: 'en-english',
    language: 'en',
    difficulty: 1,
    question: 'Which word is spelled correctly?',
    options: ['frend', 'freind', 'friend', 'freidn'],
    correct: 2,
    explanation: '"Friend" — remember: i before e, except after c! A good friend like Hermione!',
    emoji: '👯‍♀️',
    points: 10,
  },
  {
    id: 'en-002',
    subject: 'en-english',
    language: 'en',
    difficulty: 1,
    question: 'Choose the correct article: "___ owl is white and beautiful."',
    options: ['A', 'An', 'The', 'Some'],
    correct: 1,
    explanation: '"An" is used before words starting with a vowel sound. "Owl" starts with O (a vowel)!',
    emoji: '🦉',
    points: 10,
  },
  {
    id: 'en-003',
    subject: 'en-english',
    language: 'en',
    difficulty: 1,
    question: 'What is the plural of "witch"?',
    options: ['witchs', 'witches', 'witchs', 'witch'],
    correct: 1,
    explanation: 'Words ending in -ch → add "es" to make them plural! witch → witches!',
    emoji: '🧙‍♀️',
    points: 10,
  },
  {
    id: 'en-004',
    subject: 'en-english',
    language: 'en',
    difficulty: 1,
    question: 'Choose the correct past tense: "Yesterday, Mary Anne ___ her diary."',
    options: ['write', 'writed', 'wrote', 'written'],
    correct: 2,
    explanation: '"Write" is irregular! Past tense → "wrote". Mary Anne wrote in her diary every day!',
    emoji: '📔',
    points: 10,
  },
  {
    id: 'en-005',
    subject: 'en-english',
    language: 'en',
    difficulty: 1,
    question: 'What is the opposite of "happy"?',
    options: ['glad', 'joyful', 'sad', 'excited'],
    correct: 2,
    explanation: 'The opposite (antonym) of "happy" is "sad". Claudia is never sad when she\'s painting!',
    emoji: '😊',
    points: 10,
  },
  {
    id: 'en-006',
    subject: 'en-english',
    language: 'en',
    difficulty: 2,
    question: 'Choose the correct sentence:',
    options: [
      'She don\'t like spiders.',
      'She doesn\'t likes spiders.',
      'She doesn\'t like spiders.',
      'She not like spiders.',
    ],
    correct: 2,
    explanation: '"Doesn\'t" is used with he/she/it. And after "doesn\'t", the verb has no -s!',
    emoji: '🕷️',
    points: 15,
  },
  {
    id: 'en-007',
    subject: 'en-english',
    language: 'en',
    difficulty: 1,
    question: 'What does "enormous" mean?',
    options: ['tiny', 'very big', 'very fast', 'beautiful'],
    correct: 1,
    explanation: '"Enormous" means very, very big! Hagrid\'s dog Fang is enormous!',
    emoji: '🐕',
    points: 10,
  },
  {
    id: 'en-008',
    subject: 'en-english',
    language: 'en',
    difficulty: 2,
    question: 'Which word has the same sound as the "ight" in "night"?',
    options: ['sit', 'bite', 'light', 'bit'],
    correct: 2,
    explanation: '"Light" — night, light, right, fight all have the same -ight sound! Magic word families!',
    emoji: '🌙',
    points: 15,
  },
  {
    id: 'en-009',
    subject: 'en-english',
    language: 'en',
    difficulty: 1,
    question: 'Read and choose: "Kristy is the president of the Baby-Sitters Club. She is very ___."',
    options: ['shy', 'organized', 'quiet', 'bored'],
    correct: 1,
    explanation: 'Kristy is very organized — she has great ideas and runs the club perfectly!',
    emoji: '👑',
    points: 10,
  },
  {
    id: 'en-010',
    subject: 'en-english',
    language: 'en',
    difficulty: 2,
    question: 'Choose the correct form: "I ___ reading the Baby-Sitters Club right now."',
    options: ['am', 'is', 'are', 'be'],
    correct: 0,
    explanation: '"I am" + verb-ing = present continuous. I am reading, you are reading, she is reading!',
    emoji: '📗',
    points: 15,
  },
  {
    id: 'en-011',
    subject: 'en-english',
    language: 'en',
    difficulty: 1,
    question: 'Which word is a noun (a thing or person)?',
    options: ['run', 'quickly', 'beautiful', 'castle'],
    correct: 3,
    explanation: '"Castle" is a noun — it\'s a place. Hogwarts is a castle!',
    emoji: '🏰',
    points: 10,
  },
  {
    id: 'en-012',
    subject: 'en-english',
    language: 'en',
    difficulty: 2,
    question: 'Add the correct ending: "Claudia is a wonder___ artist."',
    options: ['ful', 'less', 'tion', 'ing'],
    correct: 0,
    explanation: '"Wonderful" means full of wonder — amazing! Claudia is a wonderful artist!',
    emoji: '🎨',
    points: 15,
  },
  {
    id: 'en-013',
    subject: 'en-english',
    language: 'en',
    difficulty: 1,
    question: 'Choose the correct word: "Harry Potter ___ at Hogwarts School."',
    options: ['study', 'studys', 'studies', 'studie'],
    correct: 2,
    explanation: 'With he/she/it, verbs ending in -y change to -ies! study → studies',
    emoji: '📚',
    points: 10,
  },
  {
    id: 'en-014',
    subject: 'en-english',
    language: 'en',
    difficulty: 3,
    question: 'Which sentence uses "their" correctly?',
    options: [
      'Their going to the library.',
      'The girls love their books.',
      'I want to go their.',
      'Their is a wand here.',
    ],
    correct: 1,
    explanation: '"Their" shows possession (belonging to them). "The girls love their books" — the books belong to them!',
    emoji: '📙',
    points: 20,
  },
  {
    id: 'en-015',
    subject: 'en-english',
    language: 'en',
    difficulty: 2,
    question: 'What is a synonym of "brave"?',
    options: ['scared', 'clever', 'courageous', 'funny'],
    correct: 2,
    explanation: '"Brave" and "courageous" mean the same thing. Harry Potter is both brave and courageous!',
    emoji: '🦁',
    points: 15,
  },
  {
    id: 'en-016',
    subject: 'en-english',
    language: 'en',
    difficulty: 2,
    question: 'Choose the right question word: "___ is your favourite book?"',
    options: ['Who', 'Where', 'What', 'When'],
    correct: 2,
    explanation: '"What" asks about things. "What is your favourite book?" — mine is Harry Potter!',
    emoji: '❓',
    points: 15,
  },
];
