import type { Question } from '@/types';

export const enGeneralQuestions: Question[] = [
  {
    id: 'gen-001',
    subject: 'en-general',
    language: 'en',
    difficulty: 1,
    question: 'How many continents are there on Earth?',
    options: ['5', '6', '7', '8'],
    correct: 2,
    explanation: 'There are 7 continents: Africa, Antarctica, Asia, Australia, Europe, North America, and South America!',
    emoji: '🌍',
    points: 10,
  },
  {
    id: 'gen-002',
    subject: 'en-general',
    language: 'en',
    difficulty: 1,
    question: 'What colour do you get when you mix red and yellow?',
    options: ['Purple', 'Green', 'Orange', 'Pink'],
    correct: 2,
    explanation: 'Red + Yellow = Orange! Like the colour of a beautiful sunset — or Claudia\'s favourite sweater!',
    emoji: '🎨',
    points: 10,
  },
  {
    id: 'gen-003',
    subject: 'en-general',
    language: 'en',
    difficulty: 1,
    question: 'What planet do we live on?',
    options: ['Mars', 'Venus', 'Jupiter', 'Earth'],
    correct: 3,
    explanation: 'We live on Earth! It\'s the third planet from the Sun and the only one with life — and magic schools!',
    emoji: '🌎',
    points: 10,
  },
  {
    id: 'gen-004',
    subject: 'en-general',
    language: 'en',
    difficulty: 1,
    question: 'How many days are there in a week?',
    options: ['5', '6', '7', '8'],
    correct: 2,
    explanation: 'There are 7 days in a week: Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday!',
    emoji: '📅',
    points: 10,
  },
  {
    id: 'gen-005',
    subject: 'en-general',
    language: 'en',
    difficulty: 2,
    question: 'Which of these animals is a mammal?',
    options: ['Salmon', 'Eagle', 'Dolphin', 'Frog'],
    correct: 2,
    explanation: 'Dolphins are mammals! They breathe air, are warm-blooded, and feed milk to their babies!',
    emoji: '🐬',
    points: 15,
  },
  {
    id: 'gen-006',
    subject: 'en-general',
    language: 'en',
    difficulty: 1,
    question: 'What is the capital city of France?',
    options: ['London', 'Rome', 'Paris', 'Madrid'],
    correct: 2,
    explanation: 'Paris! La ville de l\'amour — the city of love! It has the famous Eiffel Tower!',
    emoji: '🗼',
    points: 10,
  },
  {
    id: 'gen-007',
    subject: 'en-general',
    language: 'en',
    difficulty: 2,
    question: 'What do plants need to make their own food (photosynthesis)?',
    options: [
      'Water, soil, and wind',
      'Sunlight, water, and carbon dioxide',
      'Rain, insects, and heat',
      'Sunlight, sugar, and oxygen',
    ],
    correct: 1,
    explanation: 'Plants use sunlight + water + CO₂ to make food. This process is called photosynthesis!',
    emoji: '🌱',
    points: 15,
  },
  {
    id: 'gen-008',
    subject: 'en-general',
    language: 'en',
    difficulty: 1,
    question: 'How many sides does a triangle have?',
    options: ['2', '3', '4', '5'],
    correct: 1,
    explanation: 'A triangle has 3 sides and 3 angles. "Tri" means three in Latin — just like "trois" in French!',
    emoji: '🔺',
    points: 10,
  },
  {
    id: 'gen-009',
    subject: 'en-general',
    language: 'en',
    difficulty: 2,
    question: 'Which country is Montreal in?',
    options: ['United States', 'France', 'Canada', 'England'],
    correct: 2,
    explanation: 'Montreal is in Canada — the second largest French-speaking city in the world!',
    emoji: '🍁',
    points: 15,
  },
  {
    id: 'gen-010',
    subject: 'en-general',
    language: 'en',
    difficulty: 1,
    question: 'What is the largest ocean on Earth?',
    options: ['Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 'Pacific Ocean'],
    correct: 3,
    explanation: 'The Pacific Ocean is the largest — it covers more than 30% of Earth\'s surface!',
    emoji: '🌊',
    points: 10,
  },
  {
    id: 'gen-011',
    subject: 'en-general',
    language: 'en',
    difficulty: 2,
    question: 'What is the process of a caterpillar becoming a butterfly called?',
    options: ['Evolution', 'Transformation', 'Metamorphosis', 'Photosynthesis'],
    correct: 2,
    explanation: 'Metamorphosis! The caterpillar goes into a chrysalis and comes out as a beautiful butterfly!',
    emoji: '🦋',
    points: 15,
  },
  {
    id: 'gen-012',
    subject: 'en-general',
    language: 'en',
    difficulty: 1,
    question: 'How many months are there in a year?',
    options: ['10', '11', '12', '13'],
    correct: 2,
    explanation: '12 months! January, February, March... all the way to December. 30 jours ont septembre, avril, juin, et novembre!',
    emoji: '🗓️',
    points: 10,
  },
  {
    id: 'gen-013',
    subject: 'en-general',
    language: 'en',
    difficulty: 2,
    question: 'What language do most people speak in Quebec, Canada?',
    options: ['English only', 'Spanish', 'French', 'Italian'],
    correct: 2,
    explanation: 'French! Quebec is a French-speaking province of Canada. C\'est magnifique!',
    emoji: '🇨🇦',
    points: 15,
  },
  {
    id: 'gen-014',
    subject: 'en-general',
    language: 'en',
    difficulty: 2,
    question: 'Which of these is NOT a primary colour?',
    options: ['Red', 'Blue', 'Green', 'Yellow'],
    correct: 2,
    explanation: 'The primary colours are RED, BLUE, and YELLOW. Green is made by mixing blue + yellow!',
    emoji: '🌈',
    points: 15,
  },
  {
    id: 'gen-015',
    subject: 'en-general',
    language: 'en',
    difficulty: 3,
    question: 'What is the closest star to Earth (besides the Sun)?',
    options: ['Sirius', 'Polaris', 'Proxima Centauri', 'Betelgeuse'],
    correct: 2,
    explanation: 'Proxima Centauri! It\'s about 4.2 light-years away — still very, very far from our magical planet!',
    emoji: '⭐',
    points: 20,
  },
  {
    id: 'gen-016',
    subject: 'en-general',
    language: 'en',
    difficulty: 1,
    question: 'What sound does the letter "Ph" make in English?',
    options: ['"P" sound', '"F" sound', '"H" sound', '"B" sound'],
    correct: 1,
    explanation: '"Ph" makes an "F" sound! Like in "phone", "photo", "elephant" — and "Phonics"!',
    emoji: '📞',
    points: 10,
  },
];
