import type { Question } from '@/types';

export const enGeneralQuestions2: Question[] = [
  {
    id: 'gen-017', subject: 'en-general', language: 'en', difficulty: 1,
    question: 'What is the largest planet in our solar system?',
    options: ['Earth', 'Saturn', 'Jupiter', 'Mars'],
    correct: 2, explanation: 'Jupiter is the biggest planet — so big that all other planets could fit inside it! It has a famous red storm!', emoji: '🪐', points: 10,
  },
  {
    id: 'gen-018', subject: 'en-general', language: 'en', difficulty: 1,
    question: 'What do bees make?',
    options: ['Milk', 'Honey', 'Sugar', 'Wax only'],
    correct: 1, explanation: 'Bees make honey! They visit thousands of flowers to collect nectar and turn it into honey in their hive!', emoji: '🍯', points: 10,
  },
  {
    id: 'gen-019', subject: 'en-general', language: 'en', difficulty: 2,
    question: 'What is the capital of England (and the UK)?',
    options: ['Manchester', 'Birmingham', 'London', 'Edinburgh'],
    correct: 2, explanation: 'London! It\'s where King\'s Cross Station is — Platform 9¾! Also home to Big Ben and Buckingham Palace!', emoji: '🇬🇧', points: 15,
  },
  {
    id: 'gen-020', subject: 'en-general', language: 'en', difficulty: 1,
    question: 'How many legs does a spider have?',
    options: ['4', '6', '8', '10'],
    correct: 2, explanation: 'Spiders have 8 legs — they are arachnids, not insects! Insects have 6 legs. Ron is afraid of spiders!', emoji: '🕷️', points: 10,
  },
  {
    id: 'gen-021', subject: 'en-general', language: 'en', difficulty: 2,
    question: 'What is photosynthesis?',
    options: [
      'How animals breathe',
      'How plants make food using sunlight',
      'How clouds form',
      'How fish swim',
    ],
    correct: 1, explanation: 'Photosynthesis: plants use sunlight + water + CO₂ → make food (glucose) + oxygen. Plants feed the whole planet!', emoji: '🌿', points: 15,
  },
  {
    id: 'gen-022', subject: 'en-general', language: 'en', difficulty: 1,
    question: 'What is the freezing point of water in Celsius?',
    options: ['-10°C', '-5°C', '0°C', '10°C'],
    correct: 2, explanation: 'Water freezes at 0°C (32°F). Below 0°C it\'s ice, above it\'s liquid water!', emoji: '🧊', points: 10,
  },
  {
    id: 'gen-023', subject: 'en-general', language: 'en', difficulty: 2,
    question: 'Which type of rock is formed from cooled lava?',
    options: ['Sedimentary', 'Metamorphic', 'Igneous', 'Fossil'],
    correct: 2, explanation: 'Igneous rock forms when lava (molten rock) cools down! "Ignis" means fire in Latin!', emoji: '🌋', points: 15,
  },
  {
    id: 'gen-024', subject: 'en-general', language: 'en', difficulty: 1,
    question: 'What is the name of the force that pulls objects towards the Earth?',
    options: ['Magnetism', 'Gravity', 'Electricity', 'Friction'],
    correct: 1, explanation: 'Gravity! It keeps us on the ground and makes things fall. Sir Isaac Newton discovered it when an apple fell on his head!', emoji: '🍎', points: 10,
  },
  {
    id: 'gen-025', subject: 'en-general', language: 'en', difficulty: 2,
    question: 'Which country has the maple leaf on its flag?',
    options: ['Australia', 'New Zealand', 'Canada', 'Ireland'],
    correct: 2, explanation: 'Canada! The red maple leaf is the symbol of Canada. Montreal, where you live, is in Canada!', emoji: '🍁', points: 15,
  },
  {
    id: 'gen-026', subject: 'en-general', language: 'en', difficulty: 1,
    question: 'What is the tallest animal in the world?',
    options: ['Elephant', 'Giraffe', 'Camel', 'Horse'],
    correct: 1, explanation: 'The giraffe is the tallest animal — up to 6 metres tall! Its long neck helps it eat leaves from tall trees!', emoji: '🦒', points: 10,
  },
  {
    id: 'gen-027', subject: 'en-general', language: 'en', difficulty: 2,
    question: 'What is the term for animals that only eat plants?',
    options: ['Carnivore', 'Omnivore', 'Herbivore', 'Insectivore'],
    correct: 2, explanation: 'Herbivores only eat plants! "Herba" = plant. Carnivores eat meat, omnivores eat both (like us)!', emoji: '🌱', points: 15,
  },
  {
    id: 'gen-028', subject: 'en-general', language: 'en', difficulty: 1,
    question: 'How many colours are in a rainbow?',
    options: ['5', '6', '7', '8'],
    correct: 2, explanation: '7 colours: Red, Orange, Yellow, Green, Blue, Indigo, Violet. Remember: ROY G BIV!', emoji: '🌈', points: 10,
  },
  {
    id: 'gen-029', subject: 'en-general', language: 'en', difficulty: 3,
    question: 'What is the chemical symbol for water?',
    options: ['WA', 'H₂O', 'W₂O', 'HO₂'],
    correct: 1, explanation: 'H₂O = 2 Hydrogen atoms + 1 Oxygen atom. That\'s why water is called dihydrogen monoxide!', emoji: '💧', points: 20,
  },
  {
    id: 'gen-030', subject: 'en-general', language: 'en', difficulty: 1,
    question: 'What type of animal is a whale?',
    options: ['Fish', 'Reptile', 'Mammal', 'Amphibian'],
    correct: 2, explanation: 'Whales are mammals! They breathe air, are warm-blooded, and nurse their babies with milk — just like us!', emoji: '🐳', points: 10,
  },
  {
    id: 'gen-031', subject: 'en-general', language: 'en', difficulty: 2,
    question: 'What is the capital of Japan?',
    options: ['Beijing', 'Seoul', 'Tokyo', 'Bangkok'],
    correct: 2, explanation: 'Tokyo! It\'s one of the largest cities in the world and home to the famous Mount Fuji nearby!', emoji: '🇯🇵', points: 15,
  },
  {
    id: 'gen-032', subject: 'en-general', language: 'en', difficulty: 1,
    question: 'Which gas do we breathe in that we need to survive?',
    options: ['Carbon dioxide', 'Nitrogen', 'Oxygen', 'Hydrogen'],
    correct: 2, explanation: 'We breathe in Oxygen (O₂) to survive! We breathe out carbon dioxide (CO₂). Plants do the opposite!', emoji: '💨', points: 10,
  },
  {
    id: 'gen-033', subject: 'en-general', language: 'en', difficulty: 2,
    question: 'What is the name of the process by which a liquid turns into gas?',
    options: ['Condensation', 'Freezing', 'Evaporation', 'Precipitation'],
    correct: 2, explanation: 'Evaporation! When water heats up, it becomes water vapour (gas). This is part of the water cycle!', emoji: '☁️', points: 15,
  },
  {
    id: 'gen-034', subject: 'en-general', language: 'en', difficulty: 1,
    question: 'Which planet is known as the Red Planet?',
    options: ['Venus', 'Mars', 'Mercury', 'Saturn'],
    correct: 1, explanation: 'Mars is red because its surface is covered in iron oxide (rust)! NASA has sent rovers to explore it!', emoji: '🔴', points: 10,
  },
  {
    id: 'gen-035', subject: 'en-general', language: 'en', difficulty: 2,
    question: 'Who painted the Mona Lisa?',
    options: ['Pablo Picasso', 'Michelangelo', 'Leonardo da Vinci', 'Vincent van Gogh'],
    correct: 2, explanation: 'Leonardo da Vinci painted the Mona Lisa around 1503-1519. It\'s in the Louvre Museum in Paris!', emoji: '🎨', points: 15,
  },
  {
    id: 'gen-036', subject: 'en-general', language: 'en', difficulty: 1,
    question: 'What do caterpillars turn into?',
    options: ['Beetles', 'Butterflies or moths', 'Dragonflies', 'Bees'],
    correct: 1, explanation: 'Caterpillars become butterflies or moths through metamorphosis! They form a chrysalis/cocoon first!', emoji: '🦋', points: 10,
  },
  {
    id: 'gen-037', subject: 'en-general', language: 'en', difficulty: 3,
    question: 'What is the name of the world\'s longest river?',
    options: ['Amazon', 'Mississippi', 'Nile', 'Yangtze'],
    correct: 2, explanation: 'The Nile in Africa is generally considered the longest river (about 6,650 km)! The Amazon is the widest!', emoji: '🌊', points: 20,
  },
  {
    id: 'gen-038', subject: 'en-general', language: 'en', difficulty: 1,
    question: 'What instrument has black and white keys?',
    options: ['Guitar', 'Violin', 'Piano', 'Trumpet'],
    correct: 2, explanation: 'The piano has black and white keys! 88 keys total — 52 white and 36 black!', emoji: '🎹', points: 10,
  },
  {
    id: 'gen-039', subject: 'en-general', language: 'en', difficulty: 2,
    question: 'What is the study of living things called?',
    options: ['Chemistry', 'Physics', 'Biology', 'Geology'],
    correct: 2, explanation: 'Biology! "Bio" = life (Greek), "logos" = study. Biology studies animals, plants, bacteria, and all life!', emoji: '🔬', points: 15,
  },
  {
    id: 'gen-040', subject: 'en-general', language: 'en', difficulty: 1,
    question: 'What is the boiling point of water?',
    options: ['50°C', '75°C', '100°C', '150°C'],
    correct: 2, explanation: 'Water boils at 100°C (212°F) at sea level. We can use this to make tea or pasta!', emoji: '♨️', points: 10,
  },
  {
    id: 'gen-041', subject: 'en-general', language: 'en', difficulty: 2,
    question: 'In which country was the Eiffel Tower built?',
    options: ['Italy', 'Spain', 'France', 'Belgium'],
    correct: 2, explanation: 'The Eiffel Tower is in Paris, France! Built in 1889 for the World Exhibition. It\'s 330 metres tall!', emoji: '🗼', points: 15,
  },
  {
    id: 'gen-042', subject: 'en-general', language: 'en', difficulty: 1,
    question: 'What is the opposite of nocturnal?',
    options: ['Aquatic', 'Terrestrial', 'Diurnal', 'Arboreal'],
    correct: 2, explanation: '"Diurnal" = active during the day. "Nocturnal" = active at night. Owls are nocturnal, humans are diurnal!', emoji: '☀️', points: 10,
  },
  {
    id: 'gen-043', subject: 'en-general', language: 'en', difficulty: 2,
    question: 'What does DNA stand for?',
    options: [
      'Digital Network Access',
      'Deoxyribonucleic Acid',
      'Dynamic Nerve Activity',
      'Double Nucleus Atom',
    ],
    correct: 1, explanation: 'DNA = Deoxyribonucleic Acid! It\'s the molecule that carries all our genetic information — like a recipe for YOU!', emoji: '🧬', points: 15,
  },
  {
    id: 'gen-044', subject: 'en-general', language: 'en', difficulty: 1,
    question: 'Which ocean is between Europe and North America?',
    options: ['Pacific Ocean', 'Indian Ocean', 'Atlantic Ocean', 'Arctic Ocean'],
    correct: 2, explanation: 'The Atlantic Ocean separates Europe (and Africa) from the Americas! Millions cross it by plane every day!', emoji: '🌊', points: 10,
  },
  {
    id: 'gen-045', subject: 'en-general', language: 'en', difficulty: 2,
    question: 'Who wrote the famous play "Romeo and Juliet"?',
    options: ['Charles Dickens', 'William Shakespeare', 'Jane Austen', 'J.K. Rowling'],
    correct: 1, explanation: 'William Shakespeare! He wrote around 1597. He also wrote Hamlet, Macbeth, and A Midsummer Night\'s Dream!', emoji: '🎭', points: 15,
  },
  {
    id: 'gen-046', subject: 'en-general', language: 'en', difficulty: 1,
    question: 'What is the name of the closest star to Earth?',
    options: ['The Moon', 'The Sun', 'Polaris', 'Sirius'],
    correct: 1, explanation: 'The Sun is our closest star! It\'s 150 million km away. Light from the Sun takes 8 minutes to reach Earth!', emoji: '☀️', points: 10,
  },
  {
    id: 'gen-047', subject: 'en-general', language: 'en', difficulty: 3,
    question: 'What is the name of the imaginary line around the middle of the Earth?',
    options: ['Prime Meridian', 'Tropic of Cancer', 'Equator', 'Arctic Circle'],
    correct: 2, explanation: 'The Equator! It divides Earth into Northern and Southern Hemispheres. It\'s always hot near the equator!', emoji: '🌍', points: 20,
  },
  {
    id: 'gen-048', subject: 'en-general', language: 'en', difficulty: 1,
    question: 'Which of these is NOT a type of rock?',
    options: ['Igneous', 'Sedimentary', 'Metamorphic', 'Crystalline'],
    correct: 3, explanation: 'The 3 types of rock are: Igneous (from lava), Sedimentary (from layers), and Metamorphic (changed by heat/pressure)!', emoji: '🪨', points: 10,
  },
  {
    id: 'gen-049', subject: 'en-general', language: 'en', difficulty: 2,
    question: 'What instrument is used to measure temperature?',
    options: ['Barometer', 'Thermometer', 'Ruler', 'Compass'],
    correct: 1, explanation: 'A thermometer measures temperature! "Thermo" = heat (Greek), "meter" = measure!', emoji: '🌡️', points: 15,
  },
  {
    id: 'gen-050', subject: 'en-general', language: 'en', difficulty: 1,
    question: 'What do we call an animal that can live both in water and on land?',
    options: ['Reptile', 'Mammal', 'Amphibian', 'Crustacean'],
    correct: 2, explanation: 'Amphibians! "Amphi" = both, "bios" = life. Frogs, toads, and salamanders are amphibians!', emoji: '🐸', points: 10,
  },
  {
    id: 'gen-051', subject: 'en-general', language: 'en', difficulty: 2,
    question: 'Which planet has rings?',
    options: ['Mars', 'Venus', 'Saturn', 'Neptune'],
    correct: 2, explanation: 'Saturn has the most visible rings made of ice and rock! But Jupiter, Uranus, and Neptune also have rings!', emoji: '🪐', points: 15,
  },
  {
    id: 'gen-052', subject: 'en-general', language: 'en', difficulty: 1,
    question: 'What is the capital of Australia?',
    options: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'],
    correct: 2, explanation: 'Canberra! (Not Sydney — that\'s the most famous city but not the capital!) Canberra became capital in 1913!', emoji: '🦘', points: 10,
  },
  {
    id: 'gen-053', subject: 'en-general', language: 'en', difficulty: 2,
    question: 'What is the name of the process when water falls from clouds?',
    options: ['Evaporation', 'Condensation', 'Precipitation', 'Transpiration'],
    correct: 2, explanation: 'Precipitation! This includes rain, snow, sleet, and hail. It\'s part of the water cycle!', emoji: '🌧️', points: 15,
  },
  {
    id: 'gen-054', subject: 'en-general', language: 'en', difficulty: 1,
    question: 'How many bones does an adult human body have?',
    options: ['106', '206', '306', '406'],
    correct: 1, explanation: 'Adults have 206 bones! Babies are born with about 270 — some fuse together as we grow!', emoji: '🦴', points: 10,
  },
  {
    id: 'gen-055', subject: 'en-general', language: 'en', difficulty: 3,
    question: 'What is the name of the process where rocks are broken down over time by weather?',
    options: ['Erosion', 'Weathering', 'Sediment', 'Formation'],
    correct: 1, explanation: 'Weathering! Rain, wind, and temperature changes slowly break down rocks. Then erosion carries the pieces away!', emoji: '⛰️', points: 20,
  },
  {
    id: 'gen-056', subject: 'en-general', language: 'en', difficulty: 1,
    question: 'What is the name of the layer of gases surrounding Earth?',
    options: ['Atmosphere', 'Hydrosphere', 'Lithosphere', 'Biosphere'],
    correct: 0, explanation: 'The atmosphere! It protects us from the sun\'s harmful rays and gives us air to breathe!', emoji: '🌫️', points: 10,
  },
  {
    id: 'gen-057', subject: 'en-general', language: 'en', difficulty: 2,
    question: 'Which famous scientist developed the theory of relativity?',
    options: ['Isaac Newton', 'Galileo Galilei', 'Albert Einstein', 'Charles Darwin'],
    correct: 2, explanation: 'Albert Einstein! He published his theory of relativity in 1905. E = mc²! He was also a violinist!', emoji: '🔬', points: 15,
  },
  {
    id: 'gen-058', subject: 'en-general', language: 'en', difficulty: 1,
    question: 'What are the three primary colours in painting?',
    options: [
      'Red, Green, Blue',
      'Red, Yellow, Blue',
      'Orange, Purple, Green',
      'White, Black, Grey',
    ],
    correct: 1, explanation: 'In painting: Red, Yellow, Blue are primary colours! You can mix them to make all other colours!', emoji: '🎨', points: 10,
  },
  {
    id: 'gen-059', subject: 'en-general', language: 'en', difficulty: 2,
    question: 'What is the capital of Brazil?',
    options: ['Rio de Janeiro', 'São Paulo', 'Brasília', 'Salvador'],
    correct: 2, explanation: 'Brasília! (Not Rio!) Brasília was specially built to be the capital in 1960. It\'s shaped like an airplane from above!', emoji: '🇧🇷', points: 15,
  },
  {
    id: 'gen-060', subject: 'en-general', language: 'en', difficulty: 1,
    question: 'How many strings does a standard guitar have?',
    options: ['4', '5', '6', '8'],
    correct: 2, explanation: 'A standard guitar has 6 strings! A bass guitar has 4, a ukulele has 4, a violin has 4!', emoji: '🎸', points: 10,
  },
  {
    id: 'gen-061', subject: 'en-general', language: 'en', difficulty: 2,
    question: 'What do we call a group of wolves?',
    options: ['Herd', 'Flock', 'Pack', 'Pod'],
    correct: 2, explanation: 'A pack of wolves! Other animal groups: a flock of birds, a herd of cows, a pod of whales, a pride of lions!', emoji: '🐺', points: 15,
  },
  {
    id: 'gen-062', subject: 'en-general', language: 'en', difficulty: 1,
    question: 'Which country is home to the Great Wall?',
    options: ['Japan', 'India', 'China', 'Korea'],
    correct: 2, explanation: 'The Great Wall of China! It stretches over 21,000 km — built over many centuries to protect China!', emoji: '🐉', points: 10,
  },
  {
    id: 'gen-063', subject: 'en-general', language: 'en', difficulty: 3,
    question: 'What is the name of the process where a solid turns directly into gas?',
    options: ['Evaporation', 'Sublimation', 'Condensation', 'Melting'],
    correct: 1, explanation: 'Sublimation! Dry ice (solid CO₂) sublimates — it goes directly from solid to gas without becoming liquid!', emoji: '❄️', points: 20,
  },
  {
    id: 'gen-064', subject: 'en-general', language: 'en', difficulty: 1,
    question: 'What is the main language spoken in Mexico?',
    options: ['Portuguese', 'French', 'Spanish', 'English'],
    correct: 2, explanation: 'Spanish! Mexico is the largest Spanish-speaking country by population in the world!', emoji: '🇲🇽', points: 10,
  },
  {
    id: 'gen-065', subject: 'en-general', language: 'en', difficulty: 2,
    question: 'What organ in your body pumps blood?',
    options: ['Lungs', 'Liver', 'Heart', 'Brain'],
    correct: 2, explanation: 'The heart! It beats about 100,000 times a day, pumping blood through 100,000 km of blood vessels!', emoji: '❤️', points: 15,
  },
  {
    id: 'gen-066', subject: 'en-general', language: 'en', difficulty: 1,
    question: 'What is 2 × 2 × 2 × 2 (2 to the power of 4)?',
    options: ['8', '12', '16', '18'],
    correct: 2, explanation: '2⁴ = 2 × 2 × 2 × 2 = 4 × 4 = 16! Powers show repeated multiplication!', emoji: '🔢', points: 10,
  },
];
