import type { Question } from '@/types';

export const frFrancaisQuestions2: Question[] = [
  {
    id: 'fr-017', subject: 'fr-francais', language: 'fr', difficulty: 1,
    question: 'Quel est le féminin du mot "sorcier" ?',
    options: ['sorcieuse', 'sorcière', 'sorcieure', 'sorcierette'],
    correct: 1, explanation: '"Sorcier" → "sorcière". Beaucoup de mots masculins en -er font leur féminin en -ère !', emoji: '🧙', points: 10,
  },
  {
    id: 'fr-018', subject: 'fr-francais', language: 'fr', difficulty: 2,
    question: 'Conjugue "être" au présent avec "vous" : "Vous ___ des sorciers."',
    options: ['êtes', 'êtes', 'sommes', 'sont'],
    correct: 0, explanation: 'Être au présent : je suis, tu es, il est, nous sommes, vous êtes, ils sont !', emoji: '✨', points: 15,
  },
  {
    id: 'fr-019', subject: 'fr-francais', language: 'fr', difficulty: 1,
    question: 'Quel est le pluriel de "bal" ?',
    options: ['bals', 'baux', 'bales', 'bal'],
    correct: 0, explanation: '"Bal" fait "bals" au pluriel (pas "baux"). Exceptions à la règle -al → -aux !', emoji: '💃', points: 10,
  },
  {
    id: 'fr-020', subject: 'fr-francais', language: 'fr', difficulty: 2,
    question: 'Choisis le bon homophone : "Ron ___ son balai dans le couloir."',
    options: ['pose', 'pause', 'pauze', 'posent'],
    correct: 0, explanation: '"Pose" = verbe poser (il pose). "Pause" = moment de repos. Ici c\'est l\'action de poser !', emoji: '🧹', points: 15,
  },
  {
    id: 'fr-021', subject: 'fr-francais', language: 'fr', difficulty: 1,
    question: 'Quel est le nom dans cette phrase : "Le hibou blanc vole."',
    options: ['le', 'blanc', 'hibou', 'vole'],
    correct: 2, explanation: '"Hibou" est un nom commun. C\'est une chose (un animal). Le/la/les sont des articles qui précèdent le nom !', emoji: '🦉', points: 10,
  },
  {
    id: 'fr-022', subject: 'fr-francais', language: 'fr', difficulty: 2,
    question: 'Conjugue "avoir" au passé composé : "Hermione ___ la meilleure note."',
    options: ['avait', 'a eu', 'eut', 'avais'],
    correct: 1, explanation: 'Passé composé de "avoir" : j\'ai eu, tu as eu, il/elle a eu !', emoji: '📝', points: 15,
  },
  {
    id: 'fr-023', subject: 'fr-francais', language: 'fr', difficulty: 1,
    question: 'Quel est l\'adverbe dans "Harry court très vite" ?',
    options: ['Harry', 'court', 'très', 'vite'],
    correct: 2, explanation: '"Très" est un adverbe qui modifie un autre adverbe ("vite"). Il indique le degré !', emoji: '🏃', points: 10,
  },
  {
    id: 'fr-024', subject: 'fr-francais', language: 'fr', difficulty: 3,
    question: 'Quelle phrase contient un complément circonstanciel de lieu ?',
    options: [
      'Hermione lit souvent.',
      'Hermione lit à la bibliothèque.',
      'Hermione lit un livre.',
      'Hermione lit rapidement.',
    ],
    correct: 1, explanation: '"À la bibliothèque" indique OÙ Hermione lit → c\'est un CCL (Complément Circonstanciel de Lieu) !', emoji: '📍', points: 20,
  },
  {
    id: 'fr-025', subject: 'fr-francais', language: 'fr', difficulty: 1,
    question: 'Choisis la bonne orthographe : "La chouette fait du ___."',
    options: ['bruit', 'brui', 'bruyt', 'bruix'],
    correct: 0, explanation: '"Bruit" s\'écrit avec un t final muet. On peut le vérifier avec "bruyant" !', emoji: '🔊', points: 10,
  },
  {
    id: 'fr-026', subject: 'fr-francais', language: 'fr', difficulty: 2,
    question: 'Quelle est la bonne conjugaison au futur : "Demain, je ___ à Poudlard."',
    options: ['vais', 'allais', 'irai', 'allai'],
    correct: 2, explanation: '"Aller" au futur : j\'irai, tu iras, il ira, nous irons, vous irez, ils iront !', emoji: '🚂', points: 15,
  },
  {
    id: 'fr-027', subject: 'fr-francais', language: 'fr', difficulty: 1,
    question: 'Quel mot est un verbe du 1er groupe ?',
    options: ['partir', 'chanter', 'finir', 'venir'],
    correct: 1, explanation: '"Chanter" se termine par -er → 1er groupe. Ce sont les plus nombreux et les plus réguliers !', emoji: '🎵', points: 10,
  },
  {
    id: 'fr-028', subject: 'fr-francais', language: 'fr', difficulty: 2,
    question: 'Accorde correctement : "Les petites ___ volaient dans le ciel."',
    options: ['chouette', 'chouettes', 'chouetttes', 'chouetes'],
    correct: 1, explanation: '"Les chouettes" est féminin pluriel → "petites chouettes" (accord en genre et en nombre) !', emoji: '🦉', points: 15,
  },
  {
    id: 'fr-029', subject: 'fr-francais', language: 'fr', difficulty: 1,
    question: 'Quel est le synonyme de "heureux" ?',
    options: ['triste', 'content', 'fâché', 'inquiet'],
    correct: 1, explanation: '"Heureux" et "content" sont des synonymes. On peut aussi dire : joyeux, gai, radieux !', emoji: '😊', points: 10,
  },
  {
    id: 'fr-030', subject: 'fr-francais', language: 'fr', difficulty: 2,
    question: 'Conjugue "finir" au présent avec "tu" :',
    options: ['tu finis', 'tu finit', 'tu finie', 'tu fini'],
    correct: 0, explanation: 'Verbes en -ir (2ème groupe) au présent : je finis, tu finis, il finit !', emoji: '🏁', points: 15,
  },
  {
    id: 'fr-031', subject: 'fr-francais', language: 'fr', difficulty: 1,
    question: 'Quel est l\'antonyme (contraire) de "rapide" ?',
    options: ['vite', 'lent', 'fort', 'haut'],
    correct: 1, explanation: '"Lent" est le contraire de "rapide". Hermione est rapide, le troll est lent !', emoji: '🐢', points: 10,
  },
  {
    id: 'fr-032', subject: 'fr-francais', language: 'fr', difficulty: 2,
    question: 'Quel est le sujet dans : "Dans la forêt, les licornes galoppent."',
    options: ['Dans la forêt', 'les licornes', 'galoppent', 'forêt'],
    correct: 1, explanation: '"Les licornes" est le sujet : c\'est elles qui font l\'action. Astuce : qui est-ce qui galope ?', emoji: '🦄', points: 15,
  },
  {
    id: 'fr-033', subject: 'fr-francais', language: 'fr', difficulty: 1,
    question: 'Choisis le bon mot : "Il fait ___ chaud aujourd\'hui."',
    options: ['très', 'trop', 'tré', 'tres'],
    correct: 0, explanation: '"Très" signifie "beaucoup". "Trop" signifie "plus que ce qu\'il faut". Ici "très chaud" est correct !', emoji: '☀️', points: 10,
  },
  {
    id: 'fr-034', subject: 'fr-francais', language: 'fr', difficulty: 3,
    question: 'Complète avec "ou" ou "où" : "Je ne sais pas ___ il est allé, ___ s\'il reviendra."',
    options: ['où / ou', 'ou / où', 'où / où', 'ou / ou'],
    correct: 0, explanation: '"Où" = lieu (où il est allé). "Ou" = choix (ou s\'il reviendra). Astuce : remplace par "ou bien" !', emoji: '❓', points: 20,
  },
  {
    id: 'fr-035', subject: 'fr-francais', language: 'fr', difficulty: 1,
    question: 'Quel type de phrase est : "Ferme la porte !"',
    options: ['Déclarative', 'Interrogative', 'Exclamative', 'Impérative'],
    correct: 3, explanation: 'C\'est une phrase impérative (ordre/commandement). Elle se termine souvent par "!" et n\'a pas de sujet exprimé !', emoji: '🚪', points: 10,
  },
  {
    id: 'fr-036', subject: 'fr-francais', language: 'fr', difficulty: 2,
    question: 'Quel est le participe passé du verbe "prendre" ?',
    options: ['prit', 'pris', 'prand', 'prend'],
    correct: 1, explanation: '"Prendre" → participe passé "pris". J\'ai pris, tu as pris, il a pris...', emoji: '🤲', points: 15,
  },
  {
    id: 'fr-037', subject: 'fr-francais', language: 'fr', difficulty: 1,
    question: 'Quelle lettre ne se prononce pas dans "temps" ?',
    options: ['t', 'e', 'm', 'p et s'],
    correct: 3, explanation: 'Dans "temps", le p et le s sont muets. On dit juste "tan" !', emoji: '⏰', points: 10,
  },
  {
    id: 'fr-038', subject: 'fr-francais', language: 'fr', difficulty: 2,
    question: 'Complète : "Les sorciers ___ leurs baguettes magiques." (avoir, passé composé)',
    options: ['ont eu', 'avaient', 'auront', 'ont'],
    correct: 0, explanation: 'Passé composé d\'"avoir" à la 3e personne du pluriel : "ils ont eu" !', emoji: '🪄', points: 15,
  },
  {
    id: 'fr-039', subject: 'fr-francais', language: 'fr', difficulty: 1,
    question: 'Quel mot appartient à la famille de "lumière" ?',
    options: ['lune', 'lumineux', 'lieu', 'lampe'],
    correct: 1, explanation: '"Lumineux" vient du latin "lumen" (lumière), comme "lumière". Même famille, même radical !', emoji: '💡', points: 10,
  },
  {
    id: 'fr-040', subject: 'fr-francais', language: 'fr', difficulty: 3,
    question: 'Quelle phrase est à la voix passive ?',
    options: [
      'Le dragon crache du feu.',
      'Hermione lance un sort.',
      'Le sort est lancé par Hermione.',
      'Harry attrape le Vif d\'Or.',
    ],
    correct: 2, explanation: 'La voix passive : le sujet subit l\'action. "Le sort" (sujet) est lancé par Hermione (complément d\'agent) !', emoji: '⚡', points: 20,
  },
  {
    id: 'fr-041', subject: 'fr-francais', language: 'fr', difficulty: 1,
    question: 'Quel est le pluriel de "œil" ?',
    options: ['œils', 'œilles', 'yeux', 'œil'],
    correct: 2, explanation: '"Œil" fait "yeux" au pluriel. C\'est une exception ! Comme "ail" → "aulx" !', emoji: '👁️', points: 10,
  },
  {
    id: 'fr-042', subject: 'fr-francais', language: 'fr', difficulty: 2,
    question: 'Complète avec "ces" ou "ses" : "Harry range ___ affaires dans ___ malles."',
    options: ['ces / ses', 'ses / ces', 'ses / ses', 'ces / ces'],
    correct: 1, explanation: '"Ses affaires" = les affaires qui lui appartiennent (possessif). "Ces malles" = les malles montrées (démonstratif) !', emoji: '🧳', points: 15,
  },
  {
    id: 'fr-043', subject: 'fr-francais', language: 'fr', difficulty: 1,
    question: 'Combien de syllabes a le mot "bibliothèque" ?',
    options: ['3', '4', '5', '6'],
    correct: 2, explanation: 'Bi-blio-thèque = 3 syllabes. On peut taper dans ses mains pour compter !', emoji: '📚', points: 10,
  },
  {
    id: 'fr-044', subject: 'fr-francais', language: 'fr', difficulty: 2,
    question: 'Quel est l\'imparfait de "jouer" à la 1ère personne du pluriel ?',
    options: ['nous jouions', 'nous jouons', 'nous jouâmes', 'nous jouerons'],
    correct: 0, explanation: 'Imparfait = action qui durait dans le passé. "Nous jouions" : nous + radical "jou" + -ions !', emoji: '🎮', points: 15,
  },
  {
    id: 'fr-045', subject: 'fr-francais', language: 'fr', difficulty: 1,
    question: 'Quel mot est un déterminant ?',
    options: ['chat', 'beau', 'le', 'courir'],
    correct: 2, explanation: '"Le" est un article défini (déterminant). Il précède un nom : le chat, le soleil, le sorcier !', emoji: '📌', points: 10,
  },
  {
    id: 'fr-046', subject: 'fr-francais', language: 'fr', difficulty: 2,
    question: 'Choisis le bon accord : "Toutes les filles ___ contentes."',
    options: ['est', 'sont', 'a', 'a été'],
    correct: 1, explanation: '"Toutes les filles" = elles → 3e personne du pluriel → "sont". Et "contentes" s\'accorde au féminin pluriel !', emoji: '👧', points: 15,
  },
  {
    id: 'fr-047', subject: 'fr-francais', language: 'fr', difficulty: 1,
    question: 'Quel est le sens du préfixe "re-" dans "relire" ?',
    options: ['avant', 'après', 'encore une fois', 'très'],
    correct: 2, explanation: 'Le préfixe "re-" signifie "encore une fois, à nouveau". Relire = lire encore une fois !', emoji: '🔁', points: 10,
  },
  {
    id: 'fr-048', subject: 'fr-francais', language: 'fr', difficulty: 3,
    question: 'Identifie le COD : "Hermione lit son livre de potions."',
    options: ['Hermione', 'lit', 'son livre de potions', 'potions'],
    correct: 2, explanation: '"Son livre de potions" est le COD (Complément d\'Objet Direct). Qui est-ce qu\'Hermione lit ? Son livre !', emoji: '📖', points: 20,
  },
  {
    id: 'fr-049', subject: 'fr-francais', language: 'fr', difficulty: 1,
    question: 'Quelle est la bonne écriture : une ___ de chocolat ?',
    options: ['tabet', 'tablet', 'tablette', 'tablete'],
    correct: 2, explanation: '"Une tablette" de chocolat. Deux l et deux t. Une ta-blet-te !', emoji: '🍫', points: 10,
  },
  {
    id: 'fr-050', subject: 'fr-francais', language: 'fr', difficulty: 2,
    question: 'Conjugue "aller" à l\'imparfait avec "elle" :',
    options: ['elle va', 'elle allait', 'elle alla', 'elle irait'],
    correct: 1, explanation: '"Aller" à l\'imparfait : j\'allais, tu allais, elle allait, nous allions, vous alliez, ils allaient !', emoji: '🚶‍♀️', points: 15,
  },
  {
    id: 'fr-051', subject: 'fr-francais', language: 'fr', difficulty: 1,
    question: 'Quelle phrase est interrogative ?',
    options: [
      'Harry attrape le Vif d\'Or.',
      'Quel beau Vif d\'Or !',
      'Est-ce qu\'Harry attrape le Vif d\'Or ?',
      'Attrape ce Vif d\'Or.',
    ],
    correct: 2, explanation: 'La phrase interrogative pose une question et se termine par "?". On peut aussi l\'identifier par "Est-ce que" !', emoji: '❓', points: 10,
  },
  {
    id: 'fr-052', subject: 'fr-francais', language: 'fr', difficulty: 2,
    question: 'Quel est le féminin de "vieux" ?',
    options: ['vieille', 'vieuse', 'vieillette', 'vieuse'],
    correct: 0, explanation: '"Vieux" → "vieille" au féminin. Comme : beau/belle, nouveau/nouvelle !', emoji: '👴', points: 15,
  },
  {
    id: 'fr-053', subject: 'fr-francais', language: 'fr', difficulty: 1,
    question: 'Qu\'est-ce qu\'une onomatopée ?',
    options: [
      'Un mot qui vient du latin',
      'Un mot qui imite un son',
      'Un mot très long',
      'Un mot sans voyelle',
    ],
    correct: 1, explanation: 'Une onomatopée imite un son ! Exemples : "boum", "plouf", "cocorico", "miaou" !', emoji: '💥', points: 10,
  },
  {
    id: 'fr-054', subject: 'fr-francais', language: 'fr', difficulty: 2,
    question: 'Quel mot s\'écrit avec un accent circonflexe ?',
    options: ['chateau', 'forêt', 'ecole', 'pret'],
    correct: 1, explanation: '"Forêt" s\'écrit avec un accent circonflexe sur le "e" : ê. Comme bête, fête, tête !', emoji: '🌲', points: 15,
  },
  {
    id: 'fr-055', subject: 'fr-francais', language: 'fr', difficulty: 3,
    question: 'Complète avec "leur" ou "leurs" : "Les sorciers lèvent ___ baguettes. Je ___ dis bonsoir."',
    options: ['leur / leurs', 'leurs / leur', 'leur / leur', 'leurs / leurs'],
    correct: 1, explanation: '"Leurs baguettes" = adjectif possessif pluriel (plusieurs baguettes). "Je leur dis" = pronom (à eux). Astuce : si on peut mettre "son", c\'est "leur" !', emoji: '🪄', points: 20,
  },
  {
    id: 'fr-056', subject: 'fr-francais', language: 'fr', difficulty: 1,
    question: 'Combien de voyelles y a-t-il dans l\'alphabet français ?',
    options: ['5', '6', '7', '8'],
    correct: 1, explanation: '6 voyelles : A, E, I, O, U, Y ! Toutes les autres lettres sont des consonnes.', emoji: '🔤', points: 10,
  },
  {
    id: 'fr-057', subject: 'fr-francais', language: 'fr', difficulty: 2,
    question: 'Mets ce verbe au futur : "Elle (manger) une Chocogrenouille demain."',
    options: ['elle mangeait', 'elle mange', 'elle mangera', 'elle a mangé'],
    correct: 2, explanation: 'Futur de "manger" : je mangerai, tu mangeras, il mangera... On ajoute les terminaisons du futur au radical !', emoji: '🐸', points: 15,
  },
  {
    id: 'fr-058', subject: 'fr-francais', language: 'fr', difficulty: 1,
    question: 'Quel est le genre du nom "élève" ?',
    options: ['Masculin seulement', 'Féminin seulement', 'Masculin et féminin', 'Neutre'],
    correct: 2, explanation: '"Élève" est épicène (même forme au masculin et au féminin) : un élève / une élève !', emoji: '🧑‍🎓', points: 10,
  },
  {
    id: 'fr-059', subject: 'fr-francais', language: 'fr', difficulty: 2,
    question: 'Transforme à la forme négative : "Ils ont toujours leurs livres."',
    options: [
      'Ils n\'ont jamais leurs livres.',
      'Ils ont ne jamais leurs livres.',
      'Ils n\'ont pas toujours leurs livres.',
      'Ils n\'ont aucune leurs livres.',
    ],
    correct: 2, explanation: '"Toujours" → "pas toujours" ou "ne... pas toujours". La négation de "toujours" = "ne... jamais" ou "ne... pas toujours" !', emoji: '📚', points: 15,
  },
  {
    id: 'fr-060', subject: 'fr-francais', language: 'fr', difficulty: 3,
    question: 'Quel est le temps de ce verbe : "Ils auraient pu réussir." ?',
    options: ['Futur antérieur', 'Conditionnel passé', 'Plus-que-parfait', 'Imparfait'],
    correct: 1, explanation: '"Auraient pu" = conditionnel passé (auxiliaire avoir au conditionnel + participe passé) !', emoji: '🤔', points: 20,
  },
  {
    id: 'fr-061', subject: 'fr-francais', language: 'fr', difficulty: 1,
    question: 'Quel est le contraire de "silencieux" ?',
    options: ['calme', 'bruyant', 'doux', 'tranquille'],
    correct: 1, explanation: 'Le contraire de "silencieux" est "bruyant". Un troll est bruyant, une bibliothèque est silencieuse !', emoji: '🔊', points: 10,
  },
  {
    id: 'fr-062', subject: 'fr-francais', language: 'fr', difficulty: 2,
    question: 'Choisis le bon accord : "La robe ___ que tu portes est très belle."',
    options: ['bleu', 'bleus', 'bleue', 'bleues'],
    correct: 2, explanation: '"La robe" est féminin singulier → "bleue" (accord en genre et en nombre avec le nom) !', emoji: '👗', points: 15,
  },
  {
    id: 'fr-063', subject: 'fr-francais', language: 'fr', difficulty: 1,
    question: 'Que signifie le suffixe "-eur" dans "chanteur" ?',
    options: ['Petit', 'Qui fait l\'action', 'Contraire', 'De nouveau'],
    correct: 1, explanation: 'Le suffixe "-eur" désigne la personne qui fait l\'action : chanteur = celui qui chante, nageur, danseur !', emoji: '🎤', points: 10,
  },
  {
    id: 'fr-064', subject: 'fr-francais', language: 'fr', difficulty: 2,
    question: 'Identifie l\'adjectif qualificatif : "Le grand château noir était mystérieux."',
    options: ['château', 'était', 'grand / noir / mystérieux', 'Le'],
    correct: 2, explanation: '"Grand", "noir" et "mystérieux" sont des adjectifs qualificatifs : ils donnent des informations sur le château !', emoji: '🏰', points: 15,
  },
  {
    id: 'fr-065', subject: 'fr-francais', language: 'fr', difficulty: 1,
    question: 'Quel est le contraire du préfixe "in-" ?',
    options: ['sans-', 'pré-', 'Il n\'a pas de contraire', 'Le mot sans préfixe'],
    correct: 3, explanation: '"In-" crée le contraire : impossible (≠ possible), incroyable (≠ croyable), inutile (≠ utile). Retirer "in-" donne l\'antonyme !', emoji: '🔄', points: 10,
  },
  {
    id: 'fr-066', subject: 'fr-francais', language: 'fr', difficulty: 2,
    question: 'Quel est le COI dans : "Hermione écrit à Dumbledore." ?',
    options: ['Hermione', 'écrit', 'à Dumbledore', 'Dumbledore'],
    correct: 2, explanation: '"À Dumbledore" est le COI (Complément d\'Objet Indirect). Elle écrit À qui ? À Dumbledore. Introduit par une préposition !', emoji: '✉️', points: 15,
  },
];
