import type { Question } from '@/types';

export const frFrancaisQuestions: Question[] = [
  {
    id: 'fr-001',
    subject: 'fr-francais',
    language: 'fr',
    difficulty: 1,
    question: 'Quelle est la nature du mot "magique" dans "une baguette magique" ?',
    options: ['Un nom', 'Un verbe', 'Un adjectif', 'Un adverbe'],
    correct: 2,
    explanation: '"Magique" qualifie le nom "baguette". C\'est donc un adjectif !',
    emoji: '🪄',
    points: 10,
  },
  {
    id: 'fr-002',
    subject: 'fr-francais',
    language: 'fr',
    difficulty: 1,
    question: 'Mets ce groupe nominal au pluriel : "un hibou blanc"',
    options: ['des hibou blancs', 'des hiboux blancs', 'des hibous blancs', 'des hiboux blanches'],
    correct: 1,
    explanation: 'Hibou fait "hiboux" au pluriel (comme chou, genou...). Et blanc devient blancs !',
    emoji: '🦉',
    points: 10,
  },
  {
    id: 'fr-003',
    subject: 'fr-francais',
    language: 'fr',
    difficulty: 1,
    question: 'Choisis le bon homophone : "Hermione ___ très intelligente."',
    options: ['et', 'est', 'es', 'ai'],
    correct: 1,
    explanation: '"Est" = verbe être (elle est). On peut remplacer par "était" pour vérifier !',
    emoji: '📝',
    points: 10,
  },
  {
    id: 'fr-004',
    subject: 'fr-francais',
    language: 'fr',
    difficulty: 2,
    question: 'Conjugue "chanter" au présent avec "nous" : "Nous ___ une chanson de sorcier."',
    options: ['chantez', 'chantons', 'chantent', 'chante'],
    correct: 1,
    explanation: 'Nous chantons ! Les verbes en -er : je chante, tu chantes, il chante, nous chantons, vous chantez, ils chantent.',
    emoji: '🎵',
    points: 15,
  },
  {
    id: 'fr-005',
    subject: 'fr-francais',
    language: 'fr',
    difficulty: 1,
    question: 'Quel est le contraire (antonyme) du mot "courageux" ?',
    options: ['Brave', 'Fort', 'Peureux', 'Gentil'],
    correct: 2,
    explanation: 'L\'antonyme de "courageux" est "peureux" ou "lâche". Harry est courageux, il n\'est pas peureux !',
    emoji: '🦁',
    points: 10,
  },
  {
    id: 'fr-006',
    subject: 'fr-francais',
    language: 'fr',
    difficulty: 2,
    question: 'Choisis le bon accord : "Les sorcières ___ leurs baguettes."',
    options: ['lève', 'lèvent', 'lèves', 'levez'],
    correct: 1,
    explanation: '"Les sorcières" = elles = 3e personne du pluriel → "lèvent". Attention au e accent !',
    emoji: '🧙‍♀️',
    points: 15,
  },
  {
    id: 'fr-007',
    subject: 'fr-francais',
    language: 'fr',
    difficulty: 1,
    question: 'Choisis le bon homophone : "Harry ___ son balai."',
    options: ['a', 'à', 'as', 'est'],
    correct: 0,
    explanation: '"A" = verbe avoir. On peut remplacer par "avait" → Harry avait son balai. Ça marche !',
    emoji: '🧹',
    points: 10,
  },
  {
    id: 'fr-008',
    subject: 'fr-francais',
    language: 'fr',
    difficulty: 2,
    question: 'Conjugue "finir" au passé composé avec "j\'" : "J\'___ mes devoirs de potion."',
    options: ['finissais', 'finirai', 'ai fini', 'avais fini'],
    correct: 2,
    explanation: 'J\'ai fini = passé composé avec "avoir" + participe passé "fini". Bravo !',
    emoji: '📓',
    points: 15,
  },
  {
    id: 'fr-009',
    subject: 'fr-francais',
    language: 'fr',
    difficulty: 1,
    question: 'Quel est le synonyme du mot "rapide" ?',
    options: ['Lent', 'Vite', 'Fort', 'Loud'],
    correct: 1,
    explanation: '"Rapide" et "vite" veulent dire la même chose. Ron n\'est pas toujours rapide en cours !',
    emoji: '⚡',
    points: 10,
  },
  {
    id: 'fr-010',
    subject: 'fr-francais',
    language: 'fr',
    difficulty: 2,
    question: 'Quelle phrase est correctement ponctuée ?',
    options: [
      'hermione lit un livre.',
      'Hermione lit un livre.',
      'Hermione lit un livre',
      'hermione Lit un livre.',
    ],
    correct: 1,
    explanation: 'Une phrase commence par une majuscule et finit par un point. Hermione avec majuscule + point à la fin !',
    emoji: '✏️',
    points: 15,
  },
  {
    id: 'fr-011',
    subject: 'fr-francais',
    language: 'fr',
    difficulty: 2,
    question: 'Conjugue "aller" au futur avec "ils" : "Ils ___ à Poudlard l\'année prochaine."',
    options: ['vont', 'iront', 'allaient', 'aillent'],
    correct: 1,
    explanation: '"Aller" est irrégulier au futur : j\'irai, tu iras, il ira, nous irons, vous irez, ils iront !',
    emoji: '🚂',
    points: 15,
  },
  {
    id: 'fr-012',
    subject: 'fr-francais',
    language: 'fr',
    difficulty: 1,
    question: 'Trouve le verbe dans cette phrase : "La chouette blanche vole au-dessus du château."',
    options: ['chouette', 'blanche', 'vole', 'château'],
    correct: 2,
    explanation: '"Vole" est le verbe, c\'est l\'action ! On peut le conjuguer : elle vole, elle volait...',
    emoji: '🦅',
    points: 10,
  },
  {
    id: 'fr-013',
    subject: 'fr-francais',
    language: 'fr',
    difficulty: 3,
    question: 'Choisis le bon accord du participe passé : "Les potions qu\'elle a ___ étaient magiques."',
    options: ['préparé', 'préparés', 'préparée', 'préparées'],
    correct: 3,
    explanation: '"Préparées" : le COD "les potions" est féminin pluriel et est placé AVANT le verbe → accord !',
    emoji: '⚗️',
    points: 20,
  },
  {
    id: 'fr-014',
    subject: 'fr-francais',
    language: 'fr',
    difficulty: 1,
    question: 'Choisis la bonne orthographe du mot : une sorcière ___.',
    options: ['chapeau', 'chappeau', 'chapau', 'chapaux'],
    correct: 0,
    explanation: '"Chapeau" s\'écrit avec un seul p et se termine par -eau !',
    emoji: '🎩',
    points: 10,
  },
  {
    id: 'fr-015',
    subject: 'fr-francais',
    language: 'fr',
    difficulty: 2,
    question: 'Transforme cette phrase à la forme négative : "Harry mange des bonbons."',
    options: [
      'Harry ne mange pas des bonbons.',
      'Harry ne mange pas de bonbons.',
      'Harry pas mange bonbons.',
      'Harry mange ne pas bonbons.',
    ],
    correct: 1,
    explanation: 'À la forme négative : "ne...pas". Et "des" devient "de" après la négation !',
    emoji: '🍭',
    points: 15,
  },
  {
    id: 'fr-016',
    subject: 'fr-francais',
    language: 'fr',
    difficulty: 1,
    question: 'Quel mot appartient à la famille du mot "magie" ?',
    options: ['Magasin', 'Magique', 'Manger', 'Marche'],
    correct: 1,
    explanation: '"Magique" vient du même radical que "magie". Ce sont des mots de la même famille !',
    emoji: '✨',
    points: 10,
  },
];
