import type { Question } from '@/types';

export const frMathQuestions: Question[] = [
  {
    id: 'math-001',
    subject: 'fr-math',
    language: 'fr',
    difficulty: 1,
    question: 'Dans la bourse de Harry, il y a 256 Noises. Il en dépense 128 pour acheter des Chocogrenouilles. Combien lui en reste-t-il ?',
    options: ['128 Noises', '138 Noises', '118 Noises', '148 Noises'],
    correct: 0,
    explanation: '256 − 128 = 128. C\'est exactement la moitié !',
    emoji: '🪙',
    points: 10,
  },
  {
    id: 'math-002',
    subject: 'fr-math',
    language: 'fr',
    difficulty: 1,
    question: 'Hermione a lu 47 pages de son livre ce matin et 38 pages cet après-midi. Combien de pages a-t-elle lues en tout ?',
    options: ['75 pages', '85 pages', '95 pages', '82 pages'],
    correct: 1,
    explanation: '47 + 38 = 85. Hermione adore lire !',
    emoji: '📚',
    points: 10,
  },
  {
    id: 'math-003',
    subject: 'fr-math',
    language: 'fr',
    difficulty: 2,
    question: 'Sur l\'étagère de la Bibliothèque de Poudlard, il y a 342 livres de Potions et 275 livres de Transfiguration. Combien y a-t-il de livres au total ?',
    options: ['607 livres', '617 livres', '517 livres', '627 livres'],
    correct: 0,
    explanation: '342 + 275 = 617. Attends… 342 + 275 : 2+5=7, 4+7=11 (retenue), 3+2+1=6 → 617 !',
    emoji: '📖',
    points: 15,
  },
  {
    id: 'math-004',
    subject: 'fr-math',
    language: 'fr',
    difficulty: 1,
    question: 'La table de 3 : combien font 3 × 7 ?',
    options: ['18', '21', '24', '27'],
    correct: 1,
    explanation: '3 × 7 = 21. On peut aussi calculer 7 + 7 + 7 = 21 !',
    emoji: '⚗️',
    points: 10,
  },
  {
    id: 'math-005',
    subject: 'fr-math',
    language: 'fr',
    difficulty: 1,
    question: 'Ron a 5 paquets de Chocogrenouilles. Chaque paquet contient 4 grenouilles. Combien de grenouilles a-t-il en tout ?',
    options: ['9', '16', '20', '25'],
    correct: 2,
    explanation: '5 × 4 = 20. La multiplication, c\'est comme additionner 5 fois le chiffre 4 !',
    emoji: '🐸',
    points: 10,
  },
  {
    id: 'math-006',
    subject: 'fr-math',
    language: 'fr',
    difficulty: 2,
    question: 'Poudlard a 487 élèves. 253 sont des filles. Combien y a-t-il de garçons ?',
    options: ['224 garçons', '234 garçons', '244 garçons', '214 garçons'],
    correct: 1,
    explanation: '487 − 253 = 234. Super calcul !',
    emoji: '🏰',
    points: 15,
  },
  {
    id: 'math-007',
    subject: 'fr-math',
    language: 'fr',
    difficulty: 1,
    question: 'La table de 4 : combien font 4 × 6 ?',
    options: ['20', '22', '24', '28'],
    correct: 2,
    explanation: '4 × 6 = 24. Ou bien 6 × 4, c\'est pareil !',
    emoji: '✨',
    points: 10,
  },
  {
    id: 'math-008',
    subject: 'fr-math',
    language: 'fr',
    difficulty: 2,
    question: 'Harry a 750 Gallions. Il achète un balai Nimbus 2000 pour 380 Gallions. Combien lui reste-t-il ?',
    options: ['360 Gallions', '370 Gallions', '380 Gallions', '350 Gallions'],
    correct: 1,
    explanation: '750 − 380 = 370. Encore assez pour des Chocogrenouilles !',
    emoji: '🧹',
    points: 15,
  },
  {
    id: 'math-009',
    subject: 'fr-math',
    language: 'fr',
    difficulty: 1,
    question: 'Un rectangle magique a une longueur de 8 cm et une largeur de 5 cm. Quel est son périmètre ?',
    options: ['13 cm', '26 cm', '40 cm', '20 cm'],
    correct: 1,
    explanation: 'Périmètre = (8 + 5) × 2 = 13 × 2 = 26 cm. On fait le tour du rectangle !',
    emoji: '📐',
    points: 10,
  },
  {
    id: 'math-010',
    subject: 'fr-math',
    language: 'fr',
    difficulty: 1,
    question: 'La table de 5 : combien font 5 × 8 ?',
    options: ['35', '40', '45', '50'],
    correct: 1,
    explanation: '5 × 8 = 40. Les tables de 5, ça finit toujours par 0 ou 5 !',
    emoji: '⭐',
    points: 10,
  },
  {
    id: 'math-011',
    subject: 'fr-math',
    language: 'fr',
    difficulty: 2,
    question: 'Dans le train de Poudlard, il y a 9 wagons avec 32 élèves dans chaque wagon. Combien d\'élèves y a-t-il en tout ?',
    options: ['272 élèves', '288 élèves', '280 élèves', '264 élèves'],
    correct: 1,
    explanation: '9 × 32 = 288. On peut calculer 9 × 30 = 270, plus 9 × 2 = 18, donc 270 + 18 = 288 !',
    emoji: '🚂',
    points: 15,
  },
  {
    id: 'math-012',
    subject: 'fr-math',
    language: 'fr',
    difficulty: 1,
    question: 'Hermione partage équitablement 24 bonbons entre 4 amis. Combien chaque ami en reçoit-il ?',
    options: ['4 bonbons', '5 bonbons', '6 bonbons', '8 bonbons'],
    correct: 2,
    explanation: '24 ÷ 4 = 6. La division, c\'est le partage équitable !',
    emoji: '🍬',
    points: 10,
  },
  {
    id: 'math-013',
    subject: 'fr-math',
    language: 'fr',
    difficulty: 3,
    question: 'Au Quidditch, Gryffondor a marqué 5 fois le Souafle (10 points chacun) et Harry a attrapé le Vif d\'Or (150 points). Quel est le score total ?',
    options: ['160 points', '175 points', '200 points', '210 points'],
    correct: 2,
    explanation: '(5 × 10) + 150 = 50 + 150 = 200 points. GRYFFONDOR GAGNE !',
    emoji: '🏆',
    points: 20,
  },
  {
    id: 'math-014',
    subject: 'fr-math',
    language: 'fr',
    difficulty: 2,
    question: 'Poudlard reçoit 1000 lettres par jour. Combien en reçoit-il en une semaine (7 jours) ?',
    options: ['700 lettres', '7 000 lettres', '70 lettres', '700 000 lettres'],
    correct: 1,
    explanation: '1000 × 7 = 7 000. Beaucoup de hiboux !',
    emoji: '🦉',
    points: 15,
  },
  {
    id: 'math-015',
    subject: 'fr-math',
    language: 'fr',
    difficulty: 1,
    question: 'Quelle fraction représente une moitié ?',
    options: ['1/4', '1/3', '1/2', '2/3'],
    correct: 2,
    explanation: '1/2 veut dire "une part sur deux parts égales". Comme couper une pomme en deux !',
    emoji: '🍎',
    points: 10,
  },
  {
    id: 'math-016',
    subject: 'fr-math',
    language: 'fr',
    difficulty: 2,
    question: 'Dans la classe d\'Hermione, il y a 28 élèves. Un quart d\'entre eux sont dans l\'équipe de Quidditch. Combien est-ce ?',
    options: ['4 élèves', '6 élèves', '7 élèves', '8 élèves'],
    correct: 2,
    explanation: '28 ÷ 4 = 7. Un quart, c\'est diviser par 4 !',
    emoji: '🪄',
    points: 15,
  },
  {
    id: 'math-017',
    subject: 'fr-math',
    language: 'fr',
    difficulty: 3,
    question: 'Le numéro 4 Privet Drive est à 623 km de Poudlard. La maison des Weasley est à 447 km. Quelle distance sépare les deux maisons ?',
    options: ['174 km', '176 km', '186 km', '164 km'],
    correct: 1,
    explanation: '623 − 447 = 176 km. Attention à la soustraction avec emprunt !',
    emoji: '🗺️',
    points: 20,
  },
];
