import type { Question } from '@/types';

export const hpTriviaQuestions: Question[] = [
  {
    id: 'hp-001',
    subject: 'hp-trivia',
    language: 'en',
    difficulty: 1,
    question: 'What is the name of Harry Potter\'s owl?',
    options: ['Crookshanks', 'Hedwig', 'Scabbers', 'Fawkes'],
    correct: 1,
    explanation: 'Hedwig is Harry\'s beautiful white snowy owl — she carries his letters!',
    emoji: '🦉',
    points: 10,
  },
  {
    id: 'hp-002',
    subject: 'hp-trivia',
    language: 'fr',
    difficulty: 1,
    question: 'Quelle maison de Poudlard est connue pour sa bravoure et son courage ?',
    options: ['Poufsouffle', 'Serdaigle', 'Gryffondor', 'Serpentard'],
    correct: 2,
    explanation: 'Gryffondor est la maison du courage et de la bravoure. Harry, Hermione et Ron y sont !',
    emoji: '🦁',
    points: 10,
  },
  {
    id: 'hp-003',
    subject: 'hp-trivia',
    language: 'en',
    difficulty: 1,
    question: 'What sport do wizards play on broomsticks?',
    options: ['Wizard soccer', 'Quidditch', 'Broomball', 'Magic polo'],
    correct: 1,
    explanation: 'Quidditch! Harry is the youngest Seeker in a century — he catches the Golden Snitch!',
    emoji: '🧹',
    points: 10,
  },
  {
    id: 'hp-004',
    subject: 'hp-trivia',
    language: 'fr',
    difficulty: 2,
    question: 'Comment s\'appelle le sort qui repousse les sortilèges adverses ?',
    options: ['Lumos', 'Expelliarmus', 'Alohomora', 'Accio'],
    correct: 1,
    explanation: '"Expelliarmus" est le sortilège de désarmement d\'Harry. Il le lance pour faire tomber la baguette de son adversaire !',
    emoji: '⚡',
    points: 15,
  },
  {
    id: 'hp-005',
    subject: 'hp-trivia',
    language: 'en',
    difficulty: 1,
    question: 'What does "Lumos" do?',
    options: ['Opens doors', 'Creates a light at the wand tip', 'Lifts objects', 'Makes you invisible'],
    correct: 1,
    explanation: '"Lumos" creates light at the tip of your wand — like a torch! Perfect for dark corridors!',
    emoji: '💡',
    points: 10,
  },
  {
    id: 'hp-006',
    subject: 'hp-trivia',
    language: 'fr',
    difficulty: 1,
    question: 'Quel est le nom complet du professeur de Potions à Poudlard dans les premiers livres ?',
    options: ['Professeur Quirrell', 'Professeur Rogue', 'Professeur McGonagall', 'Professeur Dumbledore'],
    correct: 1,
    explanation: 'Le professeur Rogue (Severus Snape) enseigne les Potions. Il est sévère mais très compétent !',
    emoji: '⚗️',
    points: 10,
  },
  {
    id: 'hp-007',
    subject: 'hp-trivia',
    language: 'en',
    difficulty: 2,
    question: 'What does Hermione\'s cat Crookshanks look like?',
    options: ['Black with green eyes', 'White and fluffy', 'Ginger and flat-faced', 'Striped like a tiger'],
    correct: 2,
    explanation: 'Crookshanks is a big ginger cat with a squashed face — and he\'s very clever!',
    emoji: '🐱',
    points: 15,
  },
  {
    id: 'hp-008',
    subject: 'hp-trivia',
    language: 'fr',
    difficulty: 2,
    question: 'Comment s\'appelle la rue des commerces pour sorciers à Londres ?',
    options: ['Rue du Chaudron', 'Le Chemin de Traverse', 'La Ruelle Cracmol', 'La Place du Sorcier'],
    correct: 1,
    explanation: 'Le Chemin de Traverse (Diagon Alley) ! On y trouve la banque Gringotts, Ollivandre le fabricant de baguettes, et plein de boutiques magiques !',
    emoji: '🏪',
    points: 15,
  },
  {
    id: 'hp-009',
    subject: 'hp-trivia',
    language: 'en',
    difficulty: 1,
    question: 'What animal can Professor McGonagall transform into?',
    options: ['An eagle', 'A cat', 'A lion', 'An owl'],
    correct: 1,
    explanation: 'Professor McGonagall is an Animagus who can transform into a tabby cat!',
    emoji: '🐈',
    points: 10,
  },
  {
    id: 'hp-010',
    subject: 'hp-trivia',
    language: 'fr',
    difficulty: 2,
    question: 'Quel est le vrai prénom de Ron Weasley ?',
    options: ['Ronald', 'Robert', 'Ronan', 'Rodrigue'],
    correct: 0,
    explanation: 'Ron s\'appelle Ronald Bilius Weasley ! Bilius, c\'était le prénom de son oncle.',
    emoji: '🧡',
    points: 15,
  },
  {
    id: 'hp-011',
    subject: 'hp-trivia',
    language: 'en',
    difficulty: 3,
    question: 'In Latin, "Expecto Patronum" roughly means:',
    options: ['I expect a ghost', 'I await a guardian/protector', 'I cast a spell', 'I call the light'],
    correct: 1,
    explanation: '"Expecto" = I await/expect, "Patronum" = protector/guardian. The Patronus Charm summons a magical protector!',
    emoji: '🦌',
    points: 20,
  },
  {
    id: 'hp-012',
    subject: 'hp-trivia',
    language: 'fr',
    difficulty: 1,
    question: 'De quelle couleur est la cravate de la maison Gryffondor ?',
    options: ['Bleu et argent', 'Vert et argent', 'Rouge et or', 'Jaune et noir'],
    correct: 2,
    explanation: 'Rouge et or ! Les couleurs de Gryffondor représentent le feu et la bravoure !',
    emoji: '🎗️',
    points: 10,
  },
  {
    id: 'hp-013',
    subject: 'hp-trivia',
    language: 'en',
    difficulty: 2,
    question: 'What is the name of the giant spider in the Forbidden Forest?',
    options: ['Norbert', 'Fluffy', 'Aragog', 'Buckbeak'],
    correct: 2,
    explanation: 'Aragog! He is the giant Acromantula that Hagrid raised. Ron is very scared of spiders!',
    emoji: '🕷️',
    points: 15,
  },
  {
    id: 'hp-014',
    subject: 'hp-trivia',
    language: 'fr',
    difficulty: 2,
    question: 'Comment s\'appellent les bonbons qui changent de goût à Poudlard ?',
    options: ['Les Chocogrenouilles', 'Les Drages Surprises de Bertie Crochue', 'Les Réglisses Magiques', 'Les Caramels Lumos'],
    correct: 1,
    explanation: 'Les Drages Surprises de Bertie Crochue ! On peut avoir le goût de fraise... ou de chaussette sale !',
    emoji: '🍬',
    points: 15,
  },
  {
    id: 'hp-015',
    subject: 'hp-trivia',
    language: 'en',
    difficulty: 1,
    question: 'What platform do students use to board the Hogwarts Express?',
    options: ['Platform 8 and a half', 'Platform 9 and three-quarters', 'Platform 7', 'Platform 10'],
    correct: 1,
    explanation: 'Platform 9¾ at King\'s Cross Station! You have to run at the barrier to get through!',
    emoji: '🚂',
    points: 10,
  },
  {
    id: 'hp-016',
    subject: 'hp-trivia',
    language: 'fr',
    difficulty: 3,
    question: 'Combien y a-t-il de balles différentes dans un match de Quidditch ?',
    options: ['2', '3', '4', '5'],
    correct: 2,
    explanation: '4 balles : 1 Souafle (marquer des buts), 2 Cognards (attaquer les joueurs), 1 Vif d\'Or (finir le match) !',
    emoji: '🏉',
    points: 20,
  },
];
