import type { Question } from '@/types';

export const hpTriviaQuestions2: Question[] = [
  {
    id: 'hp-017', subject: 'hp-trivia', language: 'en', difficulty: 1,
    question: 'What does the spell "Alohomora" do?',
    options: ['Creates fire', 'Unlocks doors', 'Makes you invisible', 'Levitates objects'],
    correct: 1, explanation: '"Alohomora" unlocks doors and windows. Hermione uses it in Book 1 to get through locked doors!', emoji: '🔓', points: 10,
  },
  {
    id: 'hp-018', subject: 'hp-trivia', language: 'fr', difficulty: 1,
    question: 'Quel est le prénom complet de Dumbledore ?',
    options: ['Albus Perceval', 'Albus Brian', 'Albus Perceval Wulfric Brian', 'Albert Dumbledore'],
    correct: 2, explanation: 'Albus Perceval Wulfric Brian Dumbledore ! Un très long prénom pour un très grand sorcier !', emoji: '🧙‍♂️', points: 10,
  },
  {
    id: 'hp-019', subject: 'hp-trivia', language: 'en', difficulty: 2,
    question: 'What is the name of the Weasley family\'s home?',
    options: ['The Burrow', 'The Hollow', 'Shell Cottage', 'Godric\'s Hollow'],
    correct: 0, explanation: 'The Burrow! It\'s a crooked, cozy house that seems too small but always has room for more!', emoji: '🏡', points: 15,
  },
  {
    id: 'hp-020', subject: 'hp-trivia', language: 'fr', difficulty: 1,
    question: 'De quelle couleur sont les yeux de Harry Potter ?',
    options: ['Bleus', 'Marrons', 'Verts', 'Gris'],
    correct: 2, explanation: 'Harry a les yeux verts, comme sa mère Lily. C\'est une chose que de nombreux personnages remarquent dans les livres !', emoji: '👁️', points: 10,
  },
  {
    id: 'hp-021', subject: 'hp-trivia', language: 'en', difficulty: 2,
    question: 'What is the name of the house ghost of Gryffindor?',
    options: ['The Bloody Baron', 'Nearly Headless Nick', 'The Fat Friar', 'The Grey Lady'],
    correct: 1, explanation: 'Nearly Headless Nick (Sir Nicholas de Mimsy-Porpington)! His head is almost but not quite fully severed!', emoji: '👻', points: 15,
  },
  {
    id: 'hp-022', subject: 'hp-trivia', language: 'fr', difficulty: 2,
    question: 'Quel est le nom du directeur de Serpentard dans les premiers livres ?',
    options: ['Professeur Chourave', 'Professeur Chourave', 'Professeur Rogue', 'Professeur Quirrell'],
    correct: 2, explanation: 'Le professeur Rogue (Severus Snape) est le directeur de la maison Serpentard ! Il est sévère avec tout le monde sauf ses élèves préférés.', emoji: '🐍', points: 15,
  },
  {
    id: 'hp-023', subject: 'hp-trivia', language: 'en', difficulty: 1,
    question: 'What subject does Professor Sprout teach?',
    options: ['Potions', 'Herbology', 'Transfiguration', 'Defence Against the Dark Arts'],
    correct: 1, explanation: 'Professor Sprout teaches Herbology — the study of magical plants! She also heads Hufflepuff house!', emoji: '🌱', points: 10,
  },
  {
    id: 'hp-024', subject: 'hp-trivia', language: 'fr', difficulty: 2,
    question: 'Comment s\'appelle la boulangerie sucrée des sorciers dans le Chemin de Traverse ?',
    options: ['Chez Ollivandre', 'Pétunia et Fil', 'Scribbulus', 'Madam Malkins'],
    correct: 2, explanation: 'Scribbulus et d\'autres boutiques vendent des fournitures. Mais la confiserie populaire est mentionnée dans les livres pour ses Chocogrenouilles !', emoji: '🍬', points: 15,
  },
  {
    id: 'hp-025', subject: 'hp-trivia', language: 'en', difficulty: 3,
    question: 'What are the four founders of Hogwarts?',
    options: [
      'Gryffindor, Hufflepuff, Ravenclaw, Slytherin',
      'Gryffindor, Hufflepuff, Dumbledore, Slytherin',
      'Gryffindor, Ravenclaw, Slytherin, Merlin',
      'Gryffindor, Hufflepuff, Ravenclaw, Voldemort',
    ],
    correct: 0, explanation: 'The four founders: Godric Gryffindor, Helga Hufflepuff, Rowena Ravenclaw, and Salazar Slytherin!', emoji: '🏰', points: 20,
  },
  {
    id: 'hp-026', subject: 'hp-trivia', language: 'en', difficulty: 1,
    question: 'What is Voldemort\'s real name?',
    options: [
      'Tom Marvolo Riddle',
      'Tom James Potter',
      'Thomas Riddle Gaunt',
      'Lord Darkness',
    ],
    correct: 0, explanation: 'Tom Marvolo Riddle — the letters can be rearranged to spell "I am Lord Voldemort"!', emoji: '⚡', points: 10,
  },
  {
    id: 'hp-027', subject: 'hp-trivia', language: 'fr', difficulty: 2,
    question: 'Quel est le patronus d\'Harry Potter ?',
    options: ['Un loup', 'Un cerf', 'Un aigle', 'Un lion'],
    correct: 1, explanation: 'Le patronus d\'Harry est un cerf, comme celui de son père James ! Lily avait une biche. C\'est lié à "Prongs", le surnom de James.', emoji: '🦌', points: 15,
  },
  {
    id: 'hp-028', subject: 'hp-trivia', language: 'en', difficulty: 2,
    question: 'What is the name of the three-headed dog guarding the trapdoor in Book 1?',
    options: ['Cerberus', 'Fluffy', 'Rex', 'Bruno'],
    correct: 1, explanation: 'Fluffy! He was borrowed from Hagrid. The trick to making him sleep is music — just play an instrument!', emoji: '🐶', points: 15,
  },
  {
    id: 'hp-029', subject: 'hp-trivia', language: 'fr', difficulty: 1,
    question: 'Quelle est la maison de Poudlard connue pour sa loyauté et son travail ?',
    options: ['Gryffondor', 'Poufsouffle', 'Serdaigle', 'Serpentard'],
    correct: 1, explanation: 'Poufsouffle est connue pour la loyauté, la patience et le travail acharné. Les célèbres Poufsouffle : Nymphadora Tonks, Newt Scamander !', emoji: '🦡', points: 10,
  },
  {
    id: 'hp-030', subject: 'hp-trivia', language: 'en', difficulty: 2,
    question: 'What is the magical sweets shop in Hogsmeade?',
    options: ['Zonko\'s', 'Honeydukes', 'The Three Broomsticks', 'Dervish and Banges'],
    correct: 1, explanation: 'Honeydukes! Famous for Chocolate Frogs, Bertie Bott\'s Every Flavour Beans, and lots of magical sweets!', emoji: '🍫', points: 15,
  },
  {
    id: 'hp-031', subject: 'hp-trivia', language: 'fr', difficulty: 3,
    question: 'Combien de frères et sœurs a Ron Weasley ?',
    options: ['4', '5', '6', '7'],
    correct: 2, explanation: 'Ron a 6 frères et sœurs : Bill, Charlie, Percy, Fred, George et Ginny ! Il est le 6ème enfant de la famille Weasley.', emoji: '👨‍👩‍👧‍👦', points: 20,
  },
  {
    id: 'hp-032', subject: 'hp-trivia', language: 'en', difficulty: 1,
    question: 'What does the spell "Wingardium Leviosa" do?',
    options: ['Creates fire', 'Makes objects fly/levitate', 'Opens locks', 'Disarms opponents'],
    correct: 1, explanation: '"Wingardium Leviosa" levitates objects! Ron famously mispronounced it as "Wingardium Leviosaaah" and Hermione corrected him!', emoji: '🪶', points: 10,
  },
  {
    id: 'hp-033', subject: 'hp-trivia', language: 'fr', difficulty: 2,
    question: 'Quel est l\'animal magique que Hagrid élève illégalement dans sa cabane ?',
    options: ['Un Hippogriffe', 'Un Norbert (dragon)', 'Un Basilic', 'Un Centaure'],
    correct: 1, explanation: 'Norbert le dragon Novégien à crête ! Hagrid avait gagné l\'œuf et l\'avait fait éclore. Harry, Ron et Hermione ont dû le faire adopter !', emoji: '🐉', points: 15,
  },
  {
    id: 'hp-034', subject: 'hp-trivia', language: 'en', difficulty: 2,
    question: 'Who is the ghost of Ravenclaw tower?',
    options: ['The Bloody Baron', 'Nearly Headless Nick', 'The Grey Lady', 'The Fat Friar'],
    correct: 2, explanation: 'The Grey Lady! She is the ghost of Helena Ravenclaw, daughter of Rowena Ravenclaw — revealed in Book 7!', emoji: '👻', points: 15,
  },
  {
    id: 'hp-035', subject: 'hp-trivia', language: 'fr', difficulty: 1,
    question: 'Quelle est la matière où l\'on apprend à se transformer en animaux ?',
    options: ['Potions', 'Métamorphose', 'Divination', 'Soins aux créatures'],
    correct: 1, explanation: 'La Métamorphose, enseignée par le professeur McGonagall ! On y apprend à transformer les objets et les êtres vivants.', emoji: '🐈', points: 10,
  },
  {
    id: 'hp-036', subject: 'hp-trivia', language: 'en', difficulty: 3,
    question: 'What is the name of Hermione\'s Time-Turner?',
    options: ['It has no special name', 'The Tempus Turner', 'The Time Twister', 'The Golden Hourglass'],
    correct: 0, explanation: 'The Time-Turner is just called a "Time-Turner" — it\'s a magical hourglass worn around the neck that turns back time!', emoji: '⏳', points: 20,
  },
  {
    id: 'hp-037', subject: 'hp-trivia', language: 'fr', difficulty: 1,
    question: 'Où habite Harry Potter avant Poudlard ?',
    options: [
      '12, Grimmaurd Place',
      'Le Terrier',
      'Au 4, Privet Drive',
      'À Pré-au-Lard',
    ],
    correct: 2, explanation: 'Harry vivait au 4, Privet Drive à Little Whinging avec ses oncle et tante Dursley et son cousin Dudley !', emoji: '🏠', points: 10,
  },
  {
    id: 'hp-038', subject: 'hp-trivia', language: 'en', difficulty: 2,
    question: 'What magical object shows you your deepest desire?',
    options: ['The Pensieve', 'The Mirror of Erised', 'The Remembrall', 'The Sorting Hat'],
    correct: 1, explanation: 'The Mirror of Erised (Erised = "desire" spelled backwards)! Dumbledore says it shows our heart\'s deepest desire!', emoji: '🪞', points: 15,
  },
  {
    id: 'hp-039', subject: 'hp-trivia', language: 'fr', difficulty: 2,
    question: 'Quel sort est utilisé pour désarmer un adversaire ?',
    options: ['Stupefix', 'Expelliarmus', 'Petrificus Totalus', 'Impedimenta'],
    correct: 1, explanation: '"Expelliarmus" est le sort de désarmement préféré d\'Harry ! Il fait voler la baguette de l\'adversaire.', emoji: '⚡', points: 15,
  },
  {
    id: 'hp-040', subject: 'hp-trivia', language: 'en', difficulty: 1,
    question: 'What is the name of the magical bank in the wizarding world?',
    options: ['Vault of Gringotts', 'Gringotts', 'The Wizard Bank', 'Goldvault'],
    correct: 1, explanation: 'Gringotts! Run by goblins, located in Diagon Alley. It\'s said to be the safest place to keep valuables — except Hogwarts!', emoji: '🏦', points: 10,
  },
  {
    id: 'hp-041', subject: 'hp-trivia', language: 'fr', difficulty: 3,
    question: 'Qu\'est-ce qu\'un Horcruxe ?',
    options: [
      'Un sort de protection',
      'Un objet où un sorcier cache une partie de son âme',
      'Une créature magique rare',
      'Un type de potion',
    ],
    correct: 1, explanation: 'Un Horcruxe est un objet dans lequel un sorcier cache une partie de son âme. Voldemort en a créé 7 pour devenir immortel !', emoji: '💀', points: 20,
  },
  {
    id: 'hp-042', subject: 'hp-trivia', language: 'en', difficulty: 1,
    question: 'What subject does Professor Trelawney teach?',
    options: ['Arithmancy', 'Astronomy', 'Divination', 'History of Magic'],
    correct: 2, explanation: 'Professor Sybill Trelawney teaches Divination — predicting the future! Harry and Ron don\'t take it very seriously!', emoji: '🔮', points: 10,
  },
  {
    id: 'hp-043', subject: 'hp-trivia', language: 'fr', difficulty: 2,
    question: 'Quel sort "pétrifiie" complètement quelqu\'un ?',
    options: ['Stupefix', 'Petrificus Totalus', 'Immobulus', 'Glacius'],
    correct: 1, explanation: '"Petrificus Totalus" ! Il rigidifie complètement le corps. Hermione l\'utilise sur Neville dans le livre 1 !', emoji: '🧊', points: 15,
  },
  {
    id: 'hp-044', subject: 'hp-trivia', language: 'en', difficulty: 2,
    question: 'What is the name of Harry\'s first broomstick at Hogwarts?',
    options: ['Comet 260', 'Cleansweep 7', 'Nimbus 2000', 'Firebolt'],
    correct: 2, explanation: 'The Nimbus 2000! Given to Harry by Professor McGonagall when he became the youngest Gryffindor Seeker in a century!', emoji: '🧹', points: 15,
  },
  {
    id: 'hp-045', subject: 'hp-trivia', language: 'fr', difficulty: 1,
    question: 'Quel animal est l\'emblème de la maison Serdaigle ?',
    options: ['Le serpent', 'Le blaireau', 'L\'aigle', 'Le lion'],
    correct: 2, explanation: 'L\'aigle pour Serdaigle ! Gryffondor = lion, Poufsouffle = blaireau, Serpentard = serpent, Serdaigle = aigle.', emoji: '🦅', points: 10,
  },
  {
    id: 'hp-046', subject: 'hp-trivia', language: 'en', difficulty: 3,
    question: 'In what year was Harry Potter born?',
    options: ['July 31, 1979', 'July 31, 1980', 'July 31, 1981', 'July 31, 1982'],
    correct: 1, explanation: 'Harry was born on July 31, 1980! He shares his birthday with J.K. Rowling, who was also born on July 31!', emoji: '🎂', points: 20,
  },
  {
    id: 'hp-047', subject: 'hp-trivia', language: 'fr', difficulty: 2,
    question: 'Que signifie "Nox" ?',
    options: ['Allumer une lumière', 'Éteindre la lumière de la baguette', 'Créer de la fumée', 'Faire dormir'],
    correct: 1, explanation: '"Nox" éteint la lumière créée par "Lumos". Lumos = lumière, Nox = nuit (latin). Comme un interrupteur magique !', emoji: '🌑', points: 15,
  },
  {
    id: 'hp-048', subject: 'hp-trivia', language: 'en', difficulty: 1,
    question: 'What does "Hogwarts" have instead of normal electricity?',
    options: ['Solar power', 'Magic candles and torches', 'Batteries', 'Wind power'],
    correct: 1, explanation: 'Hogwarts is lit by magical candles (including floating ones in the Great Hall) and enchanted torches! Electronics don\'t work at Hogwarts!', emoji: '🕯️', points: 10,
  },
  {
    id: 'hp-049', subject: 'hp-trivia', language: 'fr', difficulty: 2,
    question: 'Qui est Dobby ?',
    options: [
      'L\'animal de compagnie des Weasley',
      'Un elfe de maison appartenant aux Malefoy',
      'Un fantôme de Poudlard',
      'Le gardien de Poudlard',
    ],
    correct: 1, explanation: 'Dobby est l\'elfe de maison des Malefoy ! Harry le libère en lui remettant une chaussette dans le livre 2. Dobby est libre !', emoji: '🧦', points: 15,
  },
  {
    id: 'hp-050', subject: 'hp-trivia', language: 'en', difficulty: 3,
    question: 'What are the three Deathly Hallows?',
    options: [
      'The Elder Wand, the Resurrection Stone, the Invisibility Cloak',
      'The Elder Wand, the Philosopher\'s Stone, the Time-Turner',
      'The Sorting Hat, the Elder Wand, the Mirror of Erised',
      'The Resurrection Stone, the Philosopher\'s Stone, the Invisibility Cloak',
    ],
    correct: 0, explanation: 'The three Deathly Hallows: The Elder Wand (most powerful), the Resurrection Stone (bring back the dead), and the Invisibility Cloak!', emoji: '☠️', points: 20,
  },
];
